// clang-format off
ksNew (16,
	keyNew (PREFIX "/array_1",
		KEY_META, "order", "0",
		KEY_META, "array", "#4",
	KEY_END),
	keyNew (PREFIX "/array_1/#0",
		KEY_VALUE, "1",
		KEY_META, "order", "1",
	KEY_END),
	keyNew (PREFIX "/array_1/#1",
		KEY_VALUE, "2",
		KEY_META, "order", "2",
	KEY_END),
	keyNew (PREFIX "/array_1/#2",
		KEY_VALUE, "3",
		KEY_META, "order", "3",
	KEY_END),
	keyNew (PREFIX "/array_1/#3",
		KEY_VALUE, "4",
		KEY_META, "order", "4",
	KEY_END),
	keyNew (PREFIX "/array_1/#4",
		KEY_VALUE, "5",
		KEY_META, "order", "5",
	KEY_END),

	keyNew (PREFIX "/array_trailing_comma_1",
		KEY_META, "order", "6",
		KEY_META, "array", "#1",
	KEY_END),
	keyNew (PREFIX "/array_trailing_comma_1/#0",
		KEY_VALUE, "1",
		KEY_META, "order", "7",
	KEY_END),
	keyNew (PREFIX "/array_trailing_comma_1/#1",
		KEY_VALUE, "2",
		KEY_META, "order", "8",
	KEY_END),

	keyNew (PREFIX "/array_trailing_comma_2",
		KEY_META, "order", "9",
		KEY_META, "array", "#1",
	KEY_END),
	keyNew (PREFIX "/array_trailing_comma_2/#0",
		KEY_VALUE, "1",
		KEY_META, "order", "10",
	KEY_END),
	keyNew (PREFIX "/array_trailing_comma_2/#1",
		KEY_VALUE, "2",
		KEY_META, "order", "11",
	KEY_END),
	keyNew (PREFIX "/array_nested",
		KEY_META, "order", "12",
		KEY_META, "array", "#2",
	KEY_END),
	keyNew (PREFIX "/array_nested/#0",
		KEY_META, "order", "13",
		KEY_META, "array", "#2",
	KEY_END),
	keyNew (PREFIX "/array_nested/#0/#0",
		KEY_VALUE, "1",
		KEY_META, "order", "14",
	KEY_END),
	keyNew (PREFIX "/array_nested/#0/#1",
		KEY_VALUE, "2",
		KEY_META, "order", "15",
	KEY_END),
	keyNew (PREFIX "/array_nested/#0/#2",
		KEY_VALUE, "3",
		KEY_META, "order", "16",
	KEY_END),
	keyNew (PREFIX "/array_nested/#1",
		KEY_META, "array", "#2",
		KEY_META, "order", "17",
	KEY_END),
	keyNew (PREFIX "/array_nested/#1/#0",
		KEY_VALUE, "4",
		KEY_META, "order", "18",
	KEY_END),
	keyNew (PREFIX "/array_nested/#1/#1",
		KEY_VALUE, "5",
		KEY_META, "order", "19",
	KEY_END),
	keyNew (PREFIX "/array_nested/#1/#2",
		KEY_VALUE, "6",
		KEY_META, "order", "20",
	KEY_END),
	keyNew (PREFIX "/array_nested/#2",
		KEY_META, "array", "#2",
		KEY_META, "order", "21",
	KEY_END),
	keyNew (PREFIX "/array_nested/#2/#0",
		KEY_VALUE, "7",
		KEY_META, "order", "22",
	KEY_END),
	keyNew (PREFIX "/array_nested/#2/#1",
		KEY_VALUE, "8",
		KEY_META, "order", "23",
	KEY_END),
	keyNew (PREFIX "/array_nested/#2/#2",
		KEY_VALUE, "9",
		KEY_META, "order", "24",
	KEY_END),

	keyNew (PREFIX "/array_empty",
		KEY_META, "order", "25",
		KEY_META, "array", "",
	KEY_END),

KS_END)
