// clang-format off
ksNew (16,
	keyNew (PREFIX "/array_1",
		ELEKTRA_KEY_META, "order", "0",
		ELEKTRA_KEY_META, "array", "#4",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_1/#0",
		ELEKTRA_KEY_VALUE, "1",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_1/#1",
		ELEKTRA_KEY_VALUE, "2",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_1/#2",
		ELEKTRA_KEY_VALUE, "3",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_1/#3",
		ELEKTRA_KEY_VALUE, "4",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_1/#4",
		ELEKTRA_KEY_VALUE, "5",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/array_trailing_comma_1",
		ELEKTRA_KEY_META, "order", "1",
		ELEKTRA_KEY_META, "array", "#1",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_trailing_comma_1/#0",
		ELEKTRA_KEY_VALUE, "1",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_trailing_comma_1/#1",
		ELEKTRA_KEY_VALUE, "2",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/array_trailing_comma_2",
		ELEKTRA_KEY_META, "order", "2",
		ELEKTRA_KEY_META, "array", "#1",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_trailing_comma_2/#0",
		ELEKTRA_KEY_VALUE, "1",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_trailing_comma_2/#1",
		ELEKTRA_KEY_VALUE, "2",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_nested",
		ELEKTRA_KEY_META, "order", "3",
		ELEKTRA_KEY_META, "array", "#2",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_nested/#0",
		ELEKTRA_KEY_META, "array", "#2",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_nested/#0/#0",
		ELEKTRA_KEY_VALUE, "1",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_nested/#0/#1",
		ELEKTRA_KEY_VALUE, "2",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_nested/#0/#2",
		ELEKTRA_KEY_VALUE, "3",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_nested/#1",
		ELEKTRA_KEY_META, "array", "#2",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_nested/#1/#0",
		ELEKTRA_KEY_VALUE, "4",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_nested/#1/#1",
		ELEKTRA_KEY_VALUE, "5",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_nested/#1/#2",
		ELEKTRA_KEY_VALUE, "6",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_nested/#2",
		ELEKTRA_KEY_META, "array", "#2",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_nested/#2/#0",
		ELEKTRA_KEY_VALUE, "7",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_nested/#2/#1",
		ELEKTRA_KEY_VALUE, "8",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/array_nested/#2/#2",
		ELEKTRA_KEY_VALUE, "9",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/array_empty",
		ELEKTRA_KEY_META, "order", "4",
		ELEKTRA_KEY_META, "array", "",
	ELEKTRA_KEY_END),

ELEKTRA_KS_END)
