// clang-format off
ksNew (16,
	keyNew (PREFIX "/a",
		ELEKTRA_KEY_VALUE, "3",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "0",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/a/b/c/d",
		ELEKTRA_KEY_VALUE, "5",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "1",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/b",
		ELEKTRA_KEY_VALUE, "hello",
		ELEKTRA_KEY_META, "tomltype", "string_basic",
		ELEKTRA_KEY_META, "type", "string",
		ELEKTRA_KEY_META, "order", "2",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/c",
		ELEKTRA_KEY_VALUE, "hello2",
		ELEKTRA_KEY_META, "tomltype", "string_literal",
		ELEKTRA_KEY_META, "type", "string",
		ELEKTRA_KEY_META, "order", "3",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/d",
		ELEKTRA_KEY_VALUE, "3.1415",
		ELEKTRA_KEY_META, "type", "double",
		ELEKTRA_KEY_META, "order", "4",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/e",
		ELEKTRA_KEY_VALUE, "+inf",
		ELEKTRA_KEY_META, "type", "double",
		ELEKTRA_KEY_META, "order", "5",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/f",
		ELEKTRA_KEY_VALUE, "-nan",
		ELEKTRA_KEY_META, "type", "double",
		ELEKTRA_KEY_META, "order", "6",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/g",
		ELEKTRA_KEY_VALUE, "1.003E-05",
		ELEKTRA_KEY_META, "type", "double",
		ELEKTRA_KEY_META, "order", "7",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/3/14",
		ELEKTRA_KEY_VALUE, "PI",
		ELEKTRA_KEY_META, "tomltype", "string_basic",
		ELEKTRA_KEY_META, "type", "string",
		ELEKTRA_KEY_META, "order", "8",
	ELEKTRA_KEY_END),
ELEKTRA_KS_END)
