// clang-format off
elektraKeysetNew (128,

	elektraKeyNew (PREFIX,
		ELEKTRA_KEY_META, "comment/#1/start", "",
		ELEKTRA_KEY_META, "comment/#1/space", "",
		ELEKTRA_KEY_META, "comment/#2", " Comment on second-to-last line",
		ELEKTRA_KEY_META, "comment/#2/start", "#",
		ELEKTRA_KEY_META, "comment/#2/space", "  ",
		ELEKTRA_KEY_META, "comment/#3", " Comment on last (non-empty) line",
		ELEKTRA_KEY_META, "comment/#3/start", "#",
		ELEKTRA_KEY_META, "comment/#3/space", "",
		ELEKTRA_KEY_META, "comment/#4/start", "",
		ELEKTRA_KEY_META, "comment/#4/space", "",
	ELEKTRA_KEY_END),

	elektraKeyNew (PREFIX "/a",
		ELEKTRA_KEY_VALUE, "3",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "0",
		ELEKTRA_KEY_META, "comment/#0", " Inline comment after keypair",
		ELEKTRA_KEY_META, "comment/#0/space", "   ",
		ELEKTRA_KEY_META, "comment/#0/start", "#",
		ELEKTRA_KEY_META, "comment/#1", " Comment on first line",
		ELEKTRA_KEY_META, "comment/#1/start", "#",
		ELEKTRA_KEY_META, "comment/#1/space", "",
		ELEKTRA_KEY_META, "comment/#2/start", "",
		ELEKTRA_KEY_META, "comment/#2/space", "",
	ELEKTRA_KEY_END),

	elektraKeyNew (PREFIX "/array",
		ELEKTRA_KEY_META, "array", "#2",
		ELEKTRA_KEY_META, "order", "1",
		ELEKTRA_KEY_META, "comment/#0", " Inline comment after array",
		ELEKTRA_KEY_META, "comment/#0/space", "   ",
		ELEKTRA_KEY_META, "comment/#0/start", "#",
		ELEKTRA_KEY_META, "comment/#1/start", "",
		ELEKTRA_KEY_META, "comment/#1/space", "",
		ELEKTRA_KEY_META, "comment/#2", " Comment #1 on full line",
		ELEKTRA_KEY_META, "comment/#2/start", "#",
		ELEKTRA_KEY_META, "comment/#2/space", "",
		ELEKTRA_KEY_META, "comment/#3", " Comment #2 on full line",
		ELEKTRA_KEY_META, "comment/#3/start", "#",
		ELEKTRA_KEY_META, "comment/#3/space", "",
		ELEKTRA_KEY_META, "comment/#4/start", "",
		ELEKTRA_KEY_META, "comment/#4/space", "",
	ELEKTRA_KEY_END),

	elektraKeyNew (PREFIX "/array/#0",
		ELEKTRA_KEY_VALUE, "1",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "comment/#0", " Comment after first value of array",
		ELEKTRA_KEY_META, "comment/#0/start", "#",
		ELEKTRA_KEY_META, "comment/#0/space", "  ",
		ELEKTRA_KEY_META, "comment/#1", " Comment directly after array opening brackets, before first value",
		ELEKTRA_KEY_META, "comment/#1/start", "#",
		ELEKTRA_KEY_META, "comment/#1/space", "   ",
	ELEKTRA_KEY_END),

	elektraKeyNew (PREFIX "/array/#1",
		ELEKTRA_KEY_VALUE, "2",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "comment/#0", " Comment after second value of array",
		ELEKTRA_KEY_META, "comment/#0/start", "#",
		ELEKTRA_KEY_META, "comment/#0/space", "  ",
	ELEKTRA_KEY_END),

	elektraKeyNew (PREFIX "/array/#2",
		ELEKTRA_KEY_VALUE, "3",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "comment/#0", " Comment after last value of array",
		ELEKTRA_KEY_META, "comment/#0/space", "   ",
		ELEKTRA_KEY_META, "comment/#0/start", "#",
	ELEKTRA_KEY_END),

	elektraKeyNew (PREFIX "/table",
		ELEKTRA_KEY_META, "tomltype", "simpletable",
		ELEKTRA_KEY_META, "order", "2",
		ELEKTRA_KEY_META, "comment/#0", " Comment after table",
		ELEKTRA_KEY_META, "comment/#0/start", "#",
		ELEKTRA_KEY_META, "comment/#0/space", " ",
		ELEKTRA_KEY_META, "comment/#1/start", "",
		ELEKTRA_KEY_META, "comment/#1/space", "",
	ELEKTRA_KEY_END),

	elektraKeyNew (PREFIX "/table_array",
		ELEKTRA_KEY_META, "array", "#0",
		ELEKTRA_KEY_META, "tomltype", "tablearray",
		ELEKTRA_KEY_META, "order", "3",
	ELEKTRA_KEY_END),

	elektraKeyNew (PREFIX "/table_array/#0",
		ELEKTRA_KEY_META, "comment/#0", " Comment after table array",
		ELEKTRA_KEY_META, "comment/#0/space", " ",
		ELEKTRA_KEY_META, "comment/#0/start", "#",
		ELEKTRA_KEY_META, "comment/#1/start", "",
		ELEKTRA_KEY_META, "comment/#1/space", "",
	ELEKTRA_KEY_END),

ELEKTRA_KS_END)


		

