// clang-format off
ksNew (32,
	keyNew (PREFIX "/basic",
		ELEKTRA_KEY_META, "tomltype", "inlinetable",
		ELEKTRA_KEY_META, "order", "0",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/basic/x",
		ELEKTRA_KEY_VALUE, "3",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "1",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/basic/y",
		ELEKTRA_KEY_VALUE, "1234",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "2",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/basic/z",
		ELEKTRA_KEY_VALUE, "500",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "3",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/inl_with_dot_keys/dot1/dot2",
		ELEKTRA_KEY_META, "tomltype", "inlinetable",
		ELEKTRA_KEY_META, "order", "4",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_with_dot_keys/dot1/dot2/a",
		ELEKTRA_KEY_VALUE, "123",
		ELEKTRA_KEY_META, "tomltype", "string_basic",
		ELEKTRA_KEY_META, "type", "string",
		ELEKTRA_KEY_META, "order", "5",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_with_dot_keys/dot1/dot2/b",
		ELEKTRA_KEY_VALUE, "456",
		ELEKTRA_KEY_META, "tomltype", "string_basic",
		ELEKTRA_KEY_META, "type", "string",
		ELEKTRA_KEY_META, "order", "6",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/inl_with_array",
		ELEKTRA_KEY_META, "tomltype", "inlinetable",
		ELEKTRA_KEY_META, "order", "7",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_with_array/int",
		ELEKTRA_KEY_META, "array", "#0",
		ELEKTRA_KEY_META, "order", "8",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_with_array/int/#0",
		ELEKTRA_KEY_VALUE, "1",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_with_array/str",
		ELEKTRA_KEY_META, "array", "#1",
		ELEKTRA_KEY_META, "order", "9",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_with_array/str/#0",
		ELEKTRA_KEY_VALUE, "test1",
		ELEKTRA_KEY_META, "tomltype", "string_basic",
		ELEKTRA_KEY_META, "type", "string",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_with_array/str/#1",
		ELEKTRA_KEY_VALUE, "test2",
		ELEKTRA_KEY_META, "tomltype", "string_basic",
		ELEKTRA_KEY_META, "type", "string",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_with_array/bool",
		ELEKTRA_KEY_META, "array", "#2",
		ELEKTRA_KEY_META, "order", "10",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_with_array/bool/#0",
		ELEKTRA_KEY_VALUE, "1",
		ELEKTRA_KEY_META, "type", "boolean",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_with_array/bool/#1",
		ELEKTRA_KEY_VALUE, "0",
		ELEKTRA_KEY_META, "type", "boolean",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_with_array/bool/#2",
		ELEKTRA_KEY_VALUE, "1",
		ELEKTRA_KEY_META, "type", "boolean",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/inl_nested",
		ELEKTRA_KEY_META, "tomltype", "inlinetable",
		ELEKTRA_KEY_META, "order", "11",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_nested/nest_1",
		ELEKTRA_KEY_META, "tomltype", "inlinetable",
		ELEKTRA_KEY_META, "order", "12",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_nested/nest_1/a",
		ELEKTRA_KEY_VALUE, "1",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "13",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_nested/nest_1/b",
		ELEKTRA_KEY_VALUE, "2",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "14",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_nested/nest_1/c",
		ELEKTRA_KEY_VALUE, "3",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "15",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_nested/nest_2",
		ELEKTRA_KEY_META, "tomltype", "inlinetable",
		ELEKTRA_KEY_META, "order", "16",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_nested/nest_2/x",
		ELEKTRA_KEY_VALUE, "4",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "17",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_nested/nest_2/y",
		ELEKTRA_KEY_VALUE, "5",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "18",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_nested/nest_2/z",
		ELEKTRA_KEY_VALUE, "6",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "19",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/inl_nested_nested",
		ELEKTRA_KEY_META, "tomltype", "inlinetable",
		ELEKTRA_KEY_META, "order", "20",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_nested_nested/nest_1",
		ELEKTRA_KEY_META, "tomltype", "inlinetable",
		ELEKTRA_KEY_META, "order", "21",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_nested_nested/nest_1/nest_2_1",
		ELEKTRA_KEY_META, "tomltype", "inlinetable",
		ELEKTRA_KEY_META, "order", "22",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_nested_nested/nest_1/nest_2_1/inner_1",
		ELEKTRA_KEY_VALUE, "666",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "23",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_nested_nested/nest_1/nest_2_1/inner_2",
		ELEKTRA_KEY_VALUE, "667",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "24",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_nested_nested/nest_1/nest_2_2",
		ELEKTRA_KEY_META, "tomltype", "inlinetable",
		ELEKTRA_KEY_META, "order", "25",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_nested_nested/nest_1/nest_2_2/inner_1",
		ELEKTRA_KEY_VALUE, "1",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "26",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/inl_nested_nested/nest_1/nest_2_2/inner_2",
		ELEKTRA_KEY_VALUE, "2",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "27",
	ELEKTRA_KEY_END),
ELEKTRA_KS_END)
