// clang-format off
ksNew (16,
	keyNew (PREFIX "/%",
		ELEKTRA_KEY_VALUE, "discouraged, but valid",
		ELEKTRA_KEY_META, "tomltype", "string_basic",
		ELEKTRA_KEY_META, "type", "string",
		ELEKTRA_KEY_META, "order", "0",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/%/%",
		ELEKTRA_KEY_VALUE, "discouraged, but valid",
		ELEKTRA_KEY_META, "tomltype", "string_basic",
		ELEKTRA_KEY_META, "type", "string",
		ELEKTRA_KEY_META, "order", "1",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/%/weird/%/very_weird/%",
		ELEKTRA_KEY_VALUE, "absolutely",
		ELEKTRA_KEY_META, "tomltype", "string_basic",
		ELEKTRA_KEY_META, "type", "string",
		ELEKTRA_KEY_META, "order", "2",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/discouraged/%/inline",
		ELEKTRA_KEY_META, "tomltype", "inlinetable",
		ELEKTRA_KEY_META, "order", "3",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/discouraged/%/inline/%",
		ELEKTRA_KEY_VALUE, "ouch",
		ELEKTRA_KEY_META, "tomltype", "string_basic",
		ELEKTRA_KEY_META, "type", "string",
		ELEKTRA_KEY_META, "order", "4",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/discouraged/%/inline/a/%",
		ELEKTRA_KEY_VALUE, "oh no",
		ELEKTRA_KEY_META, "tomltype", "string_basic",
		ELEKTRA_KEY_META, "type", "string",
		ELEKTRA_KEY_META, "order", "5",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/a/%",
		ELEKTRA_KEY_META, "tomltype", "simpletable",
		ELEKTRA_KEY_META, "order", "6",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/a/%/having_a_discouraged_super_table",
		ELEKTRA_KEY_VALUE, "1",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "7",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/1337/%/%/weird_table/%",
		ELEKTRA_KEY_META, "tomltype", "simpletable",
		ELEKTRA_KEY_META, "order", "8",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/1337/%/%/weird_table/%/horrible_super_table",
		ELEKTRA_KEY_VALUE, "yes",
		ELEKTRA_KEY_META, "tomltype", "string_literal",
		ELEKTRA_KEY_META, "type", "string",
		ELEKTRA_KEY_META, "order", "9",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/horrible_table_array/%/%/pew",
		ELEKTRA_KEY_META, "tomltype", "tablearray",
		ELEKTRA_KEY_META, "order", "10",
		ELEKTRA_KEY_META, "array", "#2",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/horrible_table_array/%/%/pew/#0/brutal",
		ELEKTRA_KEY_VALUE, "1",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "11",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/horrible_table_array/%/%/pew/#1/brutal",
		ELEKTRA_KEY_VALUE, "2",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "12",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/horrible_table_array/%/%/pew/#2/brutal",
		ELEKTRA_KEY_VALUE, "3",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "13",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/horrible_table_array/%/%/pew/#2/%",
		ELEKTRA_KEY_VALUE, "4",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "14",
	ELEKTRA_KEY_END),
ELEKTRA_KS_END)
