// clang-format off
ksNew (32,
	keyNew (PREFIX "/table_array_top",
		ELEKTRA_KEY_META, "array", "#1",
		ELEKTRA_KEY_META, "tomltype", "tablearray",
		ELEKTRA_KEY_META, "order", "0",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/table_array_top/#0/a",
		ELEKTRA_KEY_VALUE, "5",
		ELEKTRA_KEY_META, "order", "1",
		ELEKTRA_KEY_META, "type", "long_long",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/table_array_top/#0/sub1/sub2/sub3",
		ELEKTRA_KEY_META, "array", "#2",
		ELEKTRA_KEY_META, "tomltype", "tablearray",
		ELEKTRA_KEY_META, "order", "2",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/table_array_top/#0/sub1/sub2/sub3/#0/b",
		ELEKTRA_KEY_VALUE, "1",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "3",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/table_array_top/#0/sub1/sub2/sub3/#0/c",
		ELEKTRA_KEY_VALUE, "2",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "4",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/table_array_top/#0/sub1/sub2/sub3/#1/b",
		ELEKTRA_KEY_VALUE, "666",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "5",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/table_array_top/#0/sub1/sub2/sub3/#1/c",
		ELEKTRA_KEY_VALUE, "1337",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "6",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/table_array_top/#0/sub1/sub2/sub3/#2/b",
		ELEKTRA_KEY_VALUE, "1234",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "7",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/table_array_top/#0/sub1/sub2/sub3/#2/c",
		ELEKTRA_KEY_VALUE, "5678",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "8",
	ELEKTRA_KEY_END),


	keyNew (PREFIX "/table_array_top/#1/a",
		ELEKTRA_KEY_VALUE, "8",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "9",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/table_array_top/#1/sub1/sub2/sub3",
		ELEKTRA_KEY_META, "array", "#1",
		ELEKTRA_KEY_META, "tomltype", "tablearray",
		ELEKTRA_KEY_META, "order", "10",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/table_array_top/#1/sub1/sub2/sub3/#0/b",
		ELEKTRA_KEY_VALUE, "3",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "11",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/table_array_top/#1/sub1/sub2/sub3/#0/c",
		ELEKTRA_KEY_VALUE, "9",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "12",
	ELEKTRA_KEY_END),

	keyNew (PREFIX "/table_array_top/#1/sub1/sub2/sub3/#1/b",
		ELEKTRA_KEY_VALUE, "1111",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "13",
	ELEKTRA_KEY_END),
	keyNew (PREFIX "/table_array_top/#1/sub1/sub2/sub3/#1/c",
		ELEKTRA_KEY_VALUE, "2222",
		ELEKTRA_KEY_META, "type", "long_long",
		ELEKTRA_KEY_META, "order", "14",
	ELEKTRA_KEY_END),

	ELEKTRA_KS_END)
