// clang-format off
ksNew (16,
	keyNew (PREFIX "/table_array_basic",
		KEY_META, "array", "#2",
		KEY_META, "tomltype", "tablearray",
		KEY_META, "order", "0",
	KEY_END),

	keyNew (PREFIX "/table_array_basic/#0/x",
		KEY_VALUE, "1",
		KEY_META, "order", "1",
	KEY_END),
	keyNew (PREFIX "/table_array_basic/#0/y",
		KEY_VALUE, "2",
		KEY_META, "order", "2",
	KEY_END),
	keyNew (PREFIX "/table_array_basic/#0/z",
		KEY_VALUE, "3",
		KEY_META, "order", "3",
	KEY_END),

	keyNew (PREFIX "/table_array_basic/#1/x",
		KEY_VALUE, "1337",
		KEY_META, "order", "4",
	KEY_END),
	keyNew (PREFIX "/table_array_basic/#1/y",
		KEY_VALUE, "666",
		KEY_META, "order", "5",
	KEY_END),
	keyNew (PREFIX "/table_array_basic/#1/z",
		KEY_VALUE, "42",
		KEY_META, "order", "6",
	KEY_END),

	keyNew (PREFIX "/table_array_basic/#2/x",
		KEY_VALUE, "100",
		KEY_META, "order", "7",
	KEY_END),
	keyNew (PREFIX "/table_array_basic/#2/y",
		KEY_VALUE, "200",
		KEY_META, "order", "8",
	KEY_END),
	keyNew (PREFIX "/table_array_basic/#2/z",
		KEY_VALUE, "300",
		KEY_META, "order", "9",
	KEY_END),


	keyNew (PREFIX "/table_array_maybe_empty",
		KEY_META, "array", "#5",
		KEY_META, "tomltype", "tablearray",
		KEY_META, "order", "10",
	KEY_END),
	keyNew (PREFIX "/table_array_maybe_empty/#2/some_content",
		KEY_VALUE, "1",
		KEY_META, "order", "11",
	KEY_END),
	keyNew (PREFIX "/table_array_maybe_empty/#4/some_content",
		KEY_VALUE, "2",
		KEY_META, "order", "12",
	KEY_END),

KS_END)
