// clang-format off
ksNew (16,
    keyNew (PREFIX, KEY_VALUE, "@CONFIG_FILEPATH@", KEY_END),

    keyNew (PREFIX "/table_array_basic",
        KEY_META, "array", "#2",
        KEY_META, "type", "tablearray",
		KEY_META, "order", "0",
        KEY_END
    ),

    keyNew (PREFIX "/table_array_basic/#0/x",
		KEY_META, "order", "1",
		KEY_VALUE, "1",
	KEY_END),
    keyNew (PREFIX "/table_array_basic/#0/y",
		KEY_META, "order", "2",
		KEY_VALUE, "2",
	KEY_END),
    keyNew (PREFIX "/table_array_basic/#0/z",
		KEY_META, "order", "3",
		KEY_VALUE, "3",
	KEY_END),

    keyNew (PREFIX "/table_array_basic/#1/x",
		KEY_META, "order", "4",
		KEY_VALUE, "1337",
	KEY_END),
    keyNew (PREFIX "/table_array_basic/#1/y",
		KEY_META, "order", "5",
		KEY_VALUE, "666",
	KEY_END),
    keyNew (PREFIX "/table_array_basic/#1/z",
		KEY_META, "order", "6",
		KEY_VALUE, "42",
	KEY_END),

    keyNew (PREFIX "/table_array_basic/#2/x",
		KEY_META, "order", "7",
		KEY_VALUE, "100",
	KEY_END),
    keyNew (PREFIX "/table_array_basic/#2/y",
		KEY_META, "order", "8",
		KEY_VALUE, "200",
	KEY_END),
    keyNew (PREFIX "/table_array_basic/#2/z",
		KEY_META, "order", "9",
		KEY_VALUE, "300",
	KEY_END),

    KS_END
)
