#include <kdb.h>

int main() {
	KeySet ks;
	
	
	kdbOpen();
	ksInit(&ks);
	
	ksAppend(&ks,keyNew(0));     /* an empty key */
	
	ksAppend(&ks,keyNew("user/sw",0));  /* a simple key */
	
	ksAppend(&ks,keyNew("system/sw",
		KEY_FLAG_NEEDSYNC,0));        /* a key we'll retrieve from storage */
		
	ksAppend(&ks,keyNew("user/tmp/ex1",
		KEY_FLAG_HASDATA,"some data",        /* with a simple value */
		0));                                 /* end of args */
	
	ksAppend(&ks,keyNew("user/tmp/ex2",
		KEY_FLAG_HASDATA,"some data",        /* with a simple value */
		KEY_FLAG_HASPRM,0777,                /* permissions */
		0));                                 /* end of args */
	
	ksAppend(&ks,keyNew("user/tmp/ex3",
		KEY_FLAG_HASTYPE,KEY_TYPE_LINK,      /* only type */
		KEY_FLAG_HASDATA,"system/mtp/x",     /* link destination */
		KEY_FLAG_HASPRM,0654,                /* weird permissions */
		0));                                 /* end of args */
	
	ksAppend(&ks,keyNew("user/tmp/ex4",
		KEY_FLAG_HASTYPE,KEY_TYPE_BINARY,7,  /* type and value size */
		KEY_FLAG_HASCOMMENT,"value is truncated",
		KEY_FLAG_HASDATA,"some data",        /* value that will be truncated */
		KEY_FLAG_HASUID,0,                   /* root uid */
		0));                                 /* end of args */
	
	ksAppend(&ks,keyNew("user/tmp/ex5",
		KEY_FLAG_HASDATA,"some data",        /* value  */
		KEY_FLAG_HASDOMAIN,"root",           /* owner (not uid) is root */
		KEY_FLAG_HASCOMMENT,"some comment",  /* a comment */
		0));                                 /* end of args */
	
	ksAppend(&ks,keyNew("user/env/alias/ls", /* a key we know we have */
		KEY_FLAG_NEEDSYNC,                   /* retrieve from storage */
		0));                                 /* do nothing more */
	
	ksAppend(&ks,keyNew("user/env/alias/ls", /* same key, to compare in output */
		KEY_FLAG_NEEDSYNC,                   /* retrieve from storage */
		KEY_FLAG_HASDOMAIN,"root",           /* set new owner (not uid) as root */
		KEY_FLAG_HASCOMMENT,"new comment",   /* set new comment */
		0));                                 /* end of args */
	
	ksToStream(&ks,stdout,KDB_O_XMLHEADERS);
	
	ksClose(&ks);
	
	return kdbClose();
	
}



/*
 * Running this program gives me the following output:
 *
 * <?xml version="1.0" encoding="UTF-8"?>
 * <!DOCTYPE keyset PUBLIC "-//Avi Alkalay//DTD Elektra 0.1.0//EN" "http://elektra.sf.net/dtd/elektra.dtd">
 * 
 * 
 * <!-- Generated by Elektra API. Total of 10 keys. -->
 * 
 * 
 * 
 * <keyset>
 * 
 * 
 * <key name="user:aviram/sw"
 *      type="0" uid="aviram" gid="aviram" mode="0664">
 * </key>
 * 
 * 
 * 
 * 
 * 
 * <key name="system/sw"
 *      type="directory" uid="root" gid="root" mode="0755">
 * </key>
 * 
 * 
 * 
 * 
 * 
 * <key name="user:aviram/tmp/ex1"
 *      type="string" uid="aviram" gid="aviram" mode="0664">
 * 
 *      <value><![CDATA[some data]]></value>
 * </key>
 * 
 * 
 * 
 * 
 * 
 * <key name="user:aviram/tmp/ex2"
 *      type="string" uid="aviram" gid="aviram" mode="0777">
 * 
 *      <value><![CDATA[some data]]></value>
 * </key>
 * 
 * 
 * 
 * 
 * 
 * <key name="user:aviram/tmp/ex3"
 *      type="link" uid="aviram" gid="aviram" mode="0654">
 * 
 *      <value><![CDATA[system/mtp/x]]></value>
 * </key>
 * 
 * 
 * 
 * 
 * 
 * <key name="user:aviram/tmp/ex4"
 *      type="binary" uid="root" gid="aviram" mode="0664">
 * 
 *      <value><![CDATA[some da]]></value>
 *      <comment><![CDATA[value is truncated]]></comment>
 * </key>
 * 
 * 
 * 
 * 
 * 
 * <key name="user:root/tmp/ex5"
 *      type="string" uid="aviram" gid="aviram" mode="0664">
 * 
 *      <value><![CDATA[some data]]></value>
 *      <comment><![CDATA[some comment]]></comment>
 * </key>
 * 
 * 
 * 
 * <!-- See how value is the same and comment differ in next two keys -->
 * 
 * <key name="user:aviram/env/alias/ls"
 *      type="string" uid="aviram" gid="aviram" mode="0644">
 * 
 *      <value><![CDATA[ls -Fh --color=tty]]></value>
 *      <comment><![CDATA[The alias for the 'ls' command.
 * -h to show K and M bytes
 * -F to show file type indicator
 * --color=tty to show files in colors
 * 
 * ]]></comment>
 * </key>
 * 
 * 
 * 
 * 
 * 
 * <key name="user:root/env/alias/ls"
 *      type="string" uid="aviram" gid="aviram" mode="0644">
 * 
 *      <value><![CDATA[ls -Fh --color=tty]]></value>
 *      <comment><![CDATA[new comment]]></comment>
 * </key>
 * 
 * 
 * 
 * 
 * 
 * </keyset>
 *
 */
