#!/bin/sh

########################################################################
##
## This script will read network configurations under /etc/ and 
## create an equivalent registry tree under $ROOT.
##
## The correct way to run it is:
##
## # ./net-convert | sh -e
##
##
## To make tests you can do:
##
## $ ROOT=user/test ./net-convert | sh -e
##
## Avi Alkalay <avi@unix.sh>
## March 2004
##
########################################################################


[ -z "$RG" ] && RG="rg"
[ -z "$ROOT" ] && ROOT="system"

PROFILES_HOME="/etc/sysconfig/networking/profiles"

# Get list of profiles
cd $PROFILES_HOME
ls | while read profile; do
	

done
