bsd_task:
  matrix:

    - name: ðŸ˜ˆ FreeBSD 11
      freebsd_instance:
        image: freebsd-11-2-release-amd64

    - name: ðŸ˜ˆ FreeBSD 12
      freebsd_instance:
        image: freebsd-12-0-release-amd64
      env:
        PLUGINS: 'ALL;-iconv;-filecheck' # Linking the iconv library fails: https://cirrus-ci.com/task/4923537438539776

  install_script:
    - PLUGINS_KDB="$PLUGINS"; unset PLUGINS # `pkg` tries to load modules from the environment variable `PLUGINS`
    - >
      pkg install -y
      cmake
      git
      ninja
      yajl
    - export PLUGINS="$PLUGINS_KDB"; unset PLUGINS_KDB

  script:
    - mkdir build && cd build
    - cmake -GNinja -DPLUGINS="${PLUGINS:-ALL}" -DBINDINGS='ALL' -DTARGET_PLUGIN_FOLDER="" -DCMAKE_SKIP_INSTALL_RPATH=ON ..
    - ninja
    - output="$(ninja install 2>&1)" || printf '%s' "$output"

  tests_script:
    # Work around stalled process plugin and library problems on FreeBSD: https://issues.libelektra.org/2323
    - sudo mount -t fdescfs fdesc /dev/fd
    - cd build && ninja run_all
    - kdb run_all

mac_task:
  name: ðŸŽ macOS
  osx_instance:
    image: mojave-xcode-10.1

  install_script:
    - brew install cmake ninja

  script:
    - SYSTEM_DIR="$PWD/kdbsystem"
    - mkdir build && cd build
    - cmake -GNinja -DPLUGINS="${PLUGINS:-ALL}" -DBINDINGS='ALL' -DKDB_DB_SYSTEM="$SYSTEM_DIR" ..
    - ninja
    - output="$(ninja install 2>&1)" || printf '%s' "$output"

  tests_script:
    - cd build && ninja run_all
    - kdb run_all
