bsd_task:
  matrix:

    - name: ðŸ˜ˆ FreeBSD 11
      freebsd_instance:
        image: freebsd-11-2-release-amd64

    - name: ðŸ˜ˆ FreeBSD 12
      freebsd_instance:
        image: freebsd-12-0-release-amd64

  install_script:
    - >
      pkg install -y
      cmake
      git
      ninja
      yajl

  script:
    - mkdir build && cd build
    - cmake -GNinja -DPLUGINS=ALL -DBINDINGS=ALL -DTARGET_PLUGIN_FOLDER='' -DCMAKE_SKIP_INSTALL_RPATH=ON ..
    - ninja
    - output="$(ninja install 2>&1)" || printf '%s' "$output"

  tests_script:
    # Work around stalled process plugin and library problems on FreeBSD: https://issues.libelektra.org/2323
    - sudo mount -t fdescfs fdesc /dev/fd
    - cd build && ninja run_all
    - kdb run_all

mac_task:
  matrix:

    - name: ðŸŽ macOS
      osx_instance:
        image: mojave-xcode-10.1

  install_script:
    - > # Install Homebrew casks
      brew cask install java oclint
    - > # Install Homebrew formulas
      brew install
      antlr
      antlr4-cpp-runtime
      augeas
      bison
      botan
      cmake
      discount
      doxygen
      gpgme
      libgcrypt
      libgit2
      lua
      ninja
      openssl
      pkg-config
      qt
      swig
      xerces-c
      yajl
      yaml-cpp
    - | # Install Python
      brew install python@2; brew link --overwrite python@2
      brew install python || brew upgrade python
    - | # Install Ruby
      brew install ruby@2.5
      export PATH="/usr/local/opt/ruby@2.5/bin:$PATH"
    - | # Install Ruby gems
      gem install ronn test-unit --user-install --no-document

  script:
    - |
      export PATH="/usr/local/opt/ruby@2.5/bin:$PATH"
      export PATH="$HOME/.gem/ruby/$(ruby -e 'puts RUBY_VERSION' | sed 's/\.[0-9]$/.0/')/bin:$PATH"
    - SYSTEM_DIR="$PWD/kdbsystem"
    - mkdir build && cd build
    - cmake -GNinja -DPLUGINS=ALL -DBINDINGS=ALL -DKDB_DB_SYSTEM="$SYSTEM_DIR" ..
      -DRUBY_EXECUTABLE=/usr/local/opt/ruby@2.5/bin/ruby
      -DRUBY_INCLUDE_DIR=/usr/local/opt/ruby@2.5/include/ruby-2.5.0
      -DRUBY_LIBRARY=/usr/local/opt/ruby@2.5/lib/libruby.dylib
    - ninja
    - output="$(ninja install 2>&1)" || printf '%s' "$output"

  tests_script:
    - cd build && ninja run_all
    - kdb run_all
