restylers_version: 'v0.35.0'
auto: true
restylers:

  - clang-format:
      image: restyled/restyler-clang-format:12.0.0
      include:
        - "!tests/shell/gen/**/*"
        - "!**/*.js"

  - prettier:
      image: restyled/restyler-prettier:v2.2.1
  - prettier-markdown:
      image: restyled/restyler-prettier:v2.2.1
      arguments: []
  - shfmt:
      image: restyled/restyler-shfmt:v3.2.4
      arguments:
        - -s
        - -sr
