[package]
name = "elektra"
version = "0.11.1"
authors = ["PhilippGackstatter <philipp.gackstatter@student.tuwien.ac.at>"]
edition = "2018"
description = "Elektra serves as a universal and secure framework to access configuration parameters in a global, hierarchical key database."
license = "BSD-3-Clause"
homepage = "https://www.libelektra.org/"
repository = "https://master.libelektra.org/src/bindings/rust"
documentation = "https://docs.rs/elektra"
readme = "../README.md"

[features]
default = []
# Re-export the pkg-config feature from elektra-sys
pkg-config = ["elektra-sys/pkg-config"]

[dependencies]
elektra-sys = { version = "0.11.1" }
bitflags = "1.1.0"
