// clang-format off
ksNew (4,
	keyNew (PREFIX,
		KEY_VALUE, "@CONFIG_FILEPATH@",
	KEY_END),
	keyNew (PREFIX "/a",
		KEY_VALUE, "3",
		KEY_META, "order", "0",
		KEY_META, "type", "long_long",
		KEY_META, "origvalue", "3",
	KEY_END),
	keyNew (PREFIX "/a/b/c/d",
		KEY_VALUE, "5",
		KEY_META, "order", "1",
		KEY_META, "type", "long_long",
		KEY_META, "origvalue", "5",
	KEY_END),
	keyNew (PREFIX "/b",
		KEY_VALUE, "hello",
		KEY_META, "order", "2",
		KEY_META, "type", "string",
		KEY_META, "origvalue", "\"hello\"",
	KEY_END),
	keyNew (PREFIX "/c",
		KEY_VALUE, "hello2",
		KEY_META, "order", "3",
		KEY_META, "type", "string",
		KEY_META, "origvalue", "'hello2'",
	KEY_END),
	keyNew (PREFIX "/d",
		KEY_VALUE, "3.1415",
		KEY_META, "order", "4",
		KEY_META, "type", "double",
		KEY_META, "origvalue", "3.1415",
	KEY_END),
	keyNew (PREFIX "/e",
		KEY_VALUE, "+inf",
		KEY_META, "order", "5",
		KEY_META, "type", "double",
		KEY_META, "origvalue", "+inf",
	KEY_END),
	keyNew (PREFIX "/f",
		KEY_VALUE, "-nan",
		KEY_META, "order", "6",
		KEY_META, "type", "double",
		KEY_META, "origvalue", "-nan",
	KEY_END),
	keyNew (PREFIX "/3/14",
		KEY_VALUE, "PI",
		KEY_META, "type", "string",
		KEY_META, "origvalue", "\"PI\"",
		KEY_META, "order", "7",
	KEY_END),
KS_END)
