// clang-format off
ksNew (16,
keyNew (PREFIX, KEY_VALUE, "@CONFIG_FILEPATH@", KEY_END),

	keyNew (PREFIX "/multiline_basic_leading_newline",
		KEY_VALUE, "This string should be in a single line",
		KEY_META, "type", "string",
		KEY_META, "origvalue", "\"\"\"\nThis string should be in a single line\"\"\"",
		KEY_META, "order", "0",
	KEY_END),
	keyNew (PREFIX "/multiline_basic_lineending_newlines",
		KEY_VALUE, "This string should also be in a single line",
		KEY_META, "type", "string",
		KEY_META, "origvalue", "\"\"\"\nThis \\\nstring \\\nshould \\\nalso \\\nbe \\\nin \\\na \\\nsingle \\\nline\"\"\"",
		KEY_META, "order", "1",
	KEY_END),
	keyNew (PREFIX "/multiline_literal_leading_newline",
		KEY_VALUE, "Single line string",
		KEY_META, "type", "string",
		KEY_META, "origvalue", "\'\'\'\nSingle line string\'\'\'",
		KEY_META, "order", "2",
	KEY_END),
	keyNew (PREFIX "/multiline_literal_linending_newlines",
		KEY_VALUE, "Single line string",
		KEY_META, "type", "string",
		KEY_META, "origvalue", "\'\'\'\nSingle \\\nline \\\nstring\'\'\'",
		KEY_META, "order", "3",
	KEY_END),
	keyNew (PREFIX "/another_single_ling_string",
		KEY_VALUE, "The quick brown fox jumps over the lazy dog.",
		KEY_META, "type", "string",
		KEY_META, "origvalue", "\"\"\"\nThe quick brown \\\n\n\n  fox jumps over \\\n      the lazy dog.\"\"\"",
		KEY_META, "order", "4",
	KEY_END),

KS_END)
