#!/bin/sh
set -e

cd $ADTTMP

for py in /usr/share/doc/python3-elektra/examples/*.py; do
	echo "Testing $(basename $py)..."
	export TMP=$(mktemp -d --tmpdir=$PWD elektra.XXXXXXXX)
	export TMPDIR=$TMP
	export HOME=$TMP

	python3 $py
done
