FROM archlinux/base

RUN pacman -Sy --noconfirm \
    awk \
    cmake \
    diffutils \
    doxygen \
    gcc \
    git \
    graphviz \
    ninja \
    qt5-base \
    qt5-declarative \
    ruby-ronn \
    texlive-most \
    wget
