FROM alpine:edge

RUN apk update \
    && apk add --no-cache \
        build-base \
        cmake \
        doxygen \
        git \
        graphviz \
        ninja \
        ronn \
        texlive-full \
        wget
