NEL = %x85

; Printable characters from C0 set
printable =  HTAB / LF / CR
; Printable ASCII
printable =/ %x20-7e
; Next Line from C1 set
printable =/ NEL
; Characters after C1 set – Surrogate pairs
printable =/ %xa0-d7ff
; Private use characters – Replacement character
printable =/ %xe00-fffd
; All Unicode Character Starting from the Supplementary Multilingual Plain
printable =/ %x10000-10ffff

pair = *WSP "{" key ":" value "}" *WSP
key = doubleQuotedSpace
value = doubleQuotedSpace
doubleQuotedSpace =  *WSP doubleQuoted *WSP
doubleQuoted = DQUOTE content DQUOTE
content = *printable
