HelloElektra:HelloElektra.java
	/opt/jdk1.8.0_25/bin/javac -classpath jna-3.3.0.jar:. Elektra/*.java HelloElektra.java
	#
	#javac -classpath /usr/share/java/jna-3.2.7.jar:. Elektra/*.java HelloElektra.java
	#
	#ltrace -f java -classpath /usr/share/java/jna-3.2.7.jar:. HelloElektra
	/opt/jdk1.8.0_25/bin/java -classpath jna-3.3.0.jar:. HelloElektra

clean:
	rm *.class Elektra/*.class
