#!/bin/sh

# @author Dominic Jäger <e1634025@student.tuwien.ac.at>
# @brief Installs or merges a configuration file in Elektra
# @date 2019-08-20
# @tags creator

# This is a part of the preserved base path
specialPathStart="system/elektra/merge/preserve/"
# This is the path where a config file is loaded temporarily for merging
# cannot use user/elektra here and use mount at the same time
tempPath="system/tmp/merge"

our=$1
their=$2

if [ "$#" -eq 2 ]; then
	format="line"
elif [ "$#" -eq 3 ]; then
	format=$3
else
	echo "Usage is $0 <elektra path> <config file> [<format>]. It has to called as root."
	exit 1
fi

# use the file name (without path) of <config file> as special path
# in Elektra
specialPathEnd=$(basename $their)
if [ -z "$specialPathEnd" ]; then
	specialPathEnd=$their
fi
base="${specialPathStart}${specialPathEnd}"

# check if something is in <elektra path>
contentOfElektraPath=$(kdb ls $our)
if [ $? -ne 0 ]; then
	echo "ERROR: Could not use kdb ls on $our."
	exit 30
fi
if [ -z "$contentOfElektraPath" ]; then
	kdb mount --with-recommends $their $our $format
	if ! [ $? -eq 0 ]; then
		echo "Could not mount file $their."
		exit 31
	fi
	resolvedLocation=$(kdb file $our)
	if ! [ -f $resolvedLocation ]; then
		echo "Could not import file $resolvedLocation as it does not exist!"
		exit 32
	fi
	cat $resolvedLocation | kdb import $base $format
	if ! [ $? -eq 0 ]; then
		echo "Could not import file from $resolvedLocation to $base."
		exit 33
	fi
else
	# we could also import and export at this place
	# however, mounting a second time gives a more consistent user experience
	# as like this the resolver is used for <config file> each time the script
	# is called
	kdb mount -q --with-recommends $their $tempPath $format
	if ! [ $? -eq 0 ]; then
		echo "Could not mount file $their. Got code $?"
		exit 34
	fi
	kdb cmerge -f $our $tempPath $base $our $format
	if ! [ $? -eq 0 ]; then
		echo "Merging $our, $tempPath and $base into $our failed."
		exit 35
	fi
	kdb umount $tempPath
	if ! [ $? -eq 0 ]; then
		echo "umount $tempPath failed."
		exit 36
	fi
fi
