#!/bin/sh

# @author Dominic Jäger <e1634025@student.tuwien.ac.at>
# @brief Installs or merges a configuration file in Elektra
# @date 2019-08-20
# @tags creator


# This is a part of the preserved base path
specialPathStart="user/elektra/merge/preserve/"
# This is the path where a config file is loaded temporarily for merging
tempPath="user/elektra/merge/tmp"

if [ "$#" -ne 3 ]; then
	echo "Usage is $0 <elektra path> <config file> <format>"
	exit 1
fi
our=$1
their=$2
format=$3

# use the file name (without path) of <config file> as special path
# in Elektra
specialPathEnd=$(basename $their)
if [ -z "$specialPathEnd" ]; then
	specialPathEnd=$their
fi
base="${specialPathStart}${specialPathEnd}"

# check if something is in <elektra path>
if [ $(kdb ls $our | wc -c) = 0 ]; then
	cat $their | kdb import $base $format
	sudo kdb mount --with-recommends $their $our $format
else
	cat $their | kdb import $tempPath $format
	kdb cmerge -v -f $our $tempPath $base $our
	kdb rm -rf $tempPath
fi
