.TH kdb "1" "June 2012" "kdb" "User Commands"
.SH NAME
kdb \- manual page for kdb
.SH SYNOPSIS
.B kdb
\fI<command> \fR[\fIargs\fR]
.SH DESCRIPTION
kdb is a program to manage elektra's key database.
.PP
Run kdb \fB\-H\fR or \fB\--help\fR to get a list
of commands.
.PP
Run a command with \fB\-H\fR or \fB\--help\fR
to show a help text for this command.
.SH "SEE ALSO"
The full documentation for
.B kdb
is maintained within --help of the individual commands.
