[package]
name = "elektra-sys"
version = "0.11.1"
authors = ["PhilippGackstatter <philipp.gackstatter@student.tuwien.ac.at>"]
edition = "2018"
build = "build.rs"
description = "Raw bindings for libelektra."
license = "BSD-3-Clause"
homepage = "https://www.libelektra.org/"
repository = "https://master.libelektra.org/src/bindings/rust"
documentation = "https://docs.rs/elektra-sys"

[features]
default = []

[dependencies]

[build-dependencies]
bindgen = "0.66.1"
pkg-config = { version = "0.3.16", optional = true }
