int main(int argc, char**argv)
{
	char toolsfunc[][] = {"ksFromXMLfile", "ksFromXML", "ksToStream",
		"ksOutput", "ksGenerate", "keyToStream", "keyOutput",
		"keyGenerate"};
	char **

	FILE *f = fopen ("exported_symbols.h", "w");
	fprintf (f, "/* exported_symbols.h generated by exportsymbols */\n\n"
			"#include <kdbloader.h>\n");

	for (int i=1; i<argc; ++i)
	{
		if (!strcmp (argv[i], "libelektratools"))
		{
			for (int j=0; j<sizeof(toolsfunc); ++j)
			{
				fprintf(f, "extern void libelektratools_LTX_%s (void);", toolsfunc[j]);
			}
		} else {
			fprintf(f, "extern void libelektra_%s_LTX_kdbBackendFactory (void);", argv[i]);
		}
	}

	fprintf(f, "/* exported_symbols.c generated by exportsymbols.sh */\n\n"
			"#include <exported_symbols.h>\n\n"
			"kdblib_symbol kdb_exported_syms[] =\n\n"
			"{\n");

	printf ("Exporting symbols for default...");
	fprintf(f, "{\"libelektra-default\"}\n");
	fprintf(f, "{\"kdbBackendFactory\", 
}
