#include <stdio.h>

int main(int argc, char**argv)
{
	char toolsfunc[][20] = {"ksFromXMLfile", "ksFromXML", "ksToStream",
		"ksOutput", "ksGenerate", "keyToStream", "keyOutput",
		"keyGenerate"};
	int i,j;

	if (argc < 2) return 1;

	FILE *f = fopen("exported_symbols.h", "w");
	fprintf (f, "/* exported_symbols.h generated by exportsymbols */\n\n"
			"#include <kdbloader.h>\n\n\n\n");

	for (i=1; i<argc; ++i)
	{
		if (!strcmp (argv[i], "libelektratools"))
		{
			for (j=0; j<sizeof(toolsfunc); ++j)
			{
				fprintf(f, "extern void libelektratools_LTX_%s (void);\n", toolsfunc[j]);
			}
		} else {
			fprintf(f, "extern void libelektra_%s_LTX_kdbBackendFactory (void);\n\n\n\n", argv[i]);
		}
	}

	fclose (f);

	f = fopen("exported_symbols.c", "w");

	fprintf(f, "/* exported_symbols.c generated by exportsymbols.sh */\n\n"
			"#include <exported_symbols.h>\n\n"
			"kdblib_symbol kdb_exported_syms[] =\n"
			"{\n\n");

	printf ("Exporting symbols for default...\n");
	fprintf(f, "\t{\"libelektra-default\", 0},\n");
	fprintf(f, "\t{\"AkdbBackendFactory\", &libelektra_%s_LTX_kdbBackendFactory},\n", argv[1]);

	for (i=1; i<argc; ++i)
	{
		if (!strcmp (argv[i], "libelektratools"))
		{
			fprintf(f, "\t{\"libelektratools\", 0},\n");
			for (j=0; j<sizeof(toolsfunc); ++j)
			{
				fprintf(f, "\t{\"%s\", &libelektratools_%s_LTX_kdbBackendFactory},\n", toolsfunc[j], toolsfunc[j]);
			}
		} else {
			printf ("Exporting symbols for %s ...\n", argv[i]);
			fprintf(f, "\t{\"kdbBackendFactory\", &libelektra_%s_LTX_kdbBackendFactory},\n", argv[i]);
		}
	}

	fprintf(f, "\t{ 0 , 0 }\n");
	fprintf(f, "};\n");

	fclose (f);
	return 0;
}
