FROM fedora:31

RUN dnf upgrade -y && dnf install -y \
        augeas-devel \
        boost-devel \
        botan-devel \
        cmake \
        curl \
        diffutils \
        file \
        findutils \
        gcc-c++ \
        gcrypt-devel \
        git \
        glib2 \
        gpgme-devel \
        java-1.8.0-openjdk-devel \
        jna \
        libcurl-devel \
        libgit2-devel \
        libxml2-devel \
        lua-devel \
        make \
        maven \
        ninja-build \
        openssl-devel \
        python3-devel \
        qt5-devel \
        ruby-devel \
        rubygem-test-unit \
        swig \
        xerces-c-devel \
        yajl-devel \
        yaml-cpp-devel \
        zlib-devel \
    && dnf clean all -y

