FROM fedora:31

RUN dnf upgrade -y && dnf install -y \
    antlr4 \
    augeas-devel \
    boost-devel \
    cmake \
    curl \
    diffutils \
    file \
    findutils \
    gcc-c++ \
    git \
    java-1.8.0-openjdk-devel \
    jna \
    libcurl-devel \
    libgit2-devel \
    libxml2-devel \
    lua-devel \
    make \
    ninja-build \
    openssl-devel \
    python3-devel \
    ruby-devel \
    swig \
    xerces-c-devel \
    yajl-devel \
    yaml-cpp-devel \
    zlib-devel

