#ifndef ELEKTRA_PLUGIN_TOML_ERROR_CODE_H
#define ELEKTRA_PLUGIN_TOML_ERROR_CODE_H

#define ERROR_MEMORY ((int) 0xC01110)
#define ERROR_LOGICAL ((int) 0xC01300)
#define ERROR_INTERNAL ((int) 0xC01310)
#define ERROR_SYNTACTIC ((int) 0xC03100)
#define ERROR_SEMANTIC ((int) 0xC03200)

#endif // ELEKTRA_PLUGIN_TOML_ERROR_CODE_H
