#!/bin/sh

# remember the build directoy
ROOT_DIR=$PWD

# build the applications
mkdir -p build
cd build
cmake -DENABLE_ASAN=ON -DBUILD_FULL=OFF -DBUILD_SHARED=ON -DBUILD_STATIC=OFF -DBUILD_DOCUMENTATION=OFF -DPLUGINS='ALL;-fstab;-semlock' -DTOOLS='kdb;rest-backend;rest-frontend' -DCMAKE_C_FLAGS='-D_FORTIFY_SOURCE=2 -Werror=format-security -fstack-protector-strong -Wstack-protector -fPIE -pie' -DCMAKE_CXX_FLAGS='-D_FORTIFY_SOURCE=2 -Werror=format-security -fstack-protector-strong -Wstack-protector -fPIE -pie' -DCMAKE_EXE_LINKER_FLAGS='-Wl,-z,now -Wl,-z,relro' ..
make -j 3

# test the applications
make run_all

# if tests were ok, we can install
make install

# now lets first output some version information for the build log
kdb --version
# print key database for debugging
#kdb export / simpleini

# prevent jenkins from killing daemons
BUILD_ID=dontKillMe

# allow core dumps
ulimit -c unlimited

# place for core dumps (name by: echo "core_%t_%p" > /proc/sys/kernel/core_pattern)
cd /var/lib/jenkins

pstree
cat /run/elektra-rest-backend.pid || /bin/true

# then restart the backend
kdb stop-rest-backend

# sleep prevents 'address already in use'
sleep 3

kdb run-rest-backend

# we have to make sure the backend had time to start before we can go on
# (necessary because the command `kdb run-rest-backend` runs in the background)
sleep 60

# and finally re-compile the frontend
# - the old frontend is still alive and does not get taken offline (not necessary)
# - the configuration script does also take care of deleting old files,
#   every configuration run will first clean the deployment directory and copy
#   required files afterwards, ensuring an always up-to-date deployment
kdb build-rest-frontend

# create and copy api description
ELEKTRA_VERSION=$(kdb get --no-newline system/elektra/version/constants/KDB_VERSION)
apiary preview --path=$ROOT_DIR/doc/api_blueprints/snippet-sharing.apib --output=/srv/libelektra/restapi/$ELEKTRA_VERSION/snippet-sharing.html
cp $ROOT_DIR/doc/api_blueprints/snippet-sharing.apib /srv/libelektra/restapi/$ELEKTRA_VERSION/snippet-sharing.apib
rm /srv/libelektra/restapi/current
ln -s /srv/libelektra/restapi/$ELEKTRA_VERSION /srv/libelektra/restapi/current

pstree
