#!/bin/sh

SCRIPTS_DIR=$(dirname "$0")
. "${SCRIPTS_DIR}/configure-common"

cd $BUILD
cmake	-DSWIG_EXECUTABLE=/usr/bin/swig3.0 \
	-DKDB_DB_FILE="default.ini" \
	-DKDB_DB_INIT="elektra.ini" \
	-DKDB_DEFAULT_STORAGE="ini" \
	-DPLUGINS="ALL" \
	-DTOOLS="ALL" \
	-DBINDINGS="ALL" \
	$*
