#!/bin/sh

. "$(dirname "$0")/configure-common"

cd $BUILD
cmake	-DENABLE_TESTING=OFF \
	-DBUILD_TESTING=OFF \
	-DPLUGINS="wresolver;dump" \
	-DKDB_DEFAULT_RESOLVER=wresolver  \
	-DCMAKE_PIC_FLAGS="" \
	-DCXX_STD=-std=gnu++98 \
	-DCMAKE_TOOLCHAIN_FILE=$SOURCE/cmake/Toolchain/Toolchain-mingw32.cmake \
	$*
