#!/bin/sh

. "$(dirname "$0")/configure-common"

XDG_RESOLVER="resolver_mf_xp_x"

cd $BUILD
cmake	-DPLUGINS="$XDG_RESOLVER;dump;sync;error;list;timeofday;profile;mathcheck;tracer;hosts" \
	-DKDB_DEFAULT_RESOLVER="$XDG_RESOLVER" \
	$*
