#!/bin/sh

. "$(dirname "$0")/configure-common"

export JAVA_HOME=/opt/jdk1.8.0_25

cd $BUILD
cmake -DCMAKE_PREFIX_PATH=/opt/Qt5.3.0/5.3/gcc_64/lib/cmake \
	-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 \
	-DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.2 \
	-DPYTHON_LIBRARY:FILEPATH=/usr/lib/libpython3.2mu.so \
	-DENABLE_CXX11=ON \
	-DPLUGINS=ALL \
	-DTOOLS=ALL -DBINDINGS="cpp;swig_python2;swig_python3;jna" \
	$*
