#!/bin/sh

. "$(dirname "$0")/configure-common"

TOOLCHAIN_FILE="$SOURCE/cmake/Toolchain/Toolchain-mingw-w64-$(uname -m).cmake"
if [ ! -f "${TOOLCHAIN_FILE}" ]
then
	echo "Toolchain file ${TOOLCHAIN_FILE} needed for cross compiling doesn't exist"
	exit 1
fi

cd $BUILD
cmake	-DENABLE_TESTING=OFF \
	-DBUILD_TESTING=OFF \
	-DPLUGINS="wresolver;dump" \
	-DKDB_DEFAULT_RESOLVER=wresolver  \
	-DCMAKE_PIC_FLAGS="" \
	-DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE \
	$*
