#!/bin/sh

if [ $# -ne 1 ]; then
	echo "Usage: $0 source directory"
	echo
	echo "configure in debian, run script within build directory"
	exit 0
fi

cmake -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.2 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/libpython3.2mu.so -DPLUGINS=ALL -DTOOLS=ALL -DBUILD_SWIG_LUA=ON -DBUILD_SWIG_PYTHON2=ON -DBUILD_SWIG_PYTHON3=ON $1
