#!/bin/sh

. "$(dirname "$0")/configure-common"

export JAVA_HOME=/opt/jdk1.8.0_25

cd $BUILD
cmake -DCMAKE_PREFIX_PATH=/opt/Qt5.3.0/5.3/gcc_64/lib/cmake \
	-DENABLE_CXX11=ON \
	-DPLUGINS=ALL \
	-DTOOLS=ALL -DBINDINGS="cpp;swig_python2;swig_python3;jna" \
	$*
