#!/bin/sh

if [ $# -ne 1 ]; then
	echo "Usage: $0 source-directory"
	echo
	echo "configure elektra for debian unstable, run script within build directory"
	exit 0
fi

cmake -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.4 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.4dm.so -DPLUGINS=ALL -DTOOLS=ALL -DBINDINGS=ALL $1
