#!/bin/sh
#
# @author Markus Raab <elektra@markus-raab.org>
# @desc Configure a debian build
# @date 02.09.2014
# @tags configure
# @system debian

. "$(dirname "$0")/configure-common"

cd $BUILD
cmake	-DSWIG_EXECUTABLE=/usr/bin/swig3.0 \
	-DPLUGINS="ALL" \
	-DTOOLS="ALL" \
	-DBINDINGS="ALL" \
	$*
