#!/bin/sh

set -e

if [ $# -ne 1 ]; then
	echo "$0 <new-pluginname>"
	echo "allows you to copy templates and rename them properly"
	echo "This was meant for creating new plugins"
	exit 0
fi


First=`echo $1 | sed 's/\<./\u&/'`
ALL=`echo $1 | sed 's/.*/\U&/'`

cp -r template $1
cd $1
mv template.c $1.c
mv template.h $1.h

sed -i s/TEMPLATE/$ALL/g $1.c $1.h CMakeLists.txt
sed -i s/Template/$First/g $1.c $1.h CMakeLists.txt
sed -i s/template/$1/g $1.c $1.h CMakeLists.txt
