#!/bin/sh
#
# @author Kurt Micheli <kurt.micheli@libelektra.org>
# @brief Draws a graph out of the opmphm output (opmphmGraph.dot)
# @date 25.11.2016
# @tags generator, creator

if [ -z "$1" ]
then
	echo "Usage $0 <dotfile>"
	exit
fi
dot -Tpng "$1" -o "$(cut -d "." -f1<<<"$1").png"
