#!/bin/sh

set -x

SELF=$(readlink -f "$0")
SCRIPTS=$(dirname "$SELF")
SOURCE=$(dirname "$SCRIPTS")
OUTPUT=$SOURCE/doc/images/plugins.dot

echo "strict digraph G {" > $OUTPUT
#echo "	ratio = fill;" >> $OUTPUT
#echo "	size = \"13,13\";" >> $OUTPUT
echo "	splines = true;" >> $OUTPUT
echo
#echo "	plugin [shape=Mdiamond];" >> $OUTPUT
for i in `ls src/plugins`
do
	if [ -d "src/plugins/$i" ]
	then
		r="src/plugins/$i/README.md"
		p=`grep "^- infos/provides" "$r" | cut -f 2 -d =`
		if [ "$p" ]
		then
			p=`echo "$p" | tr '/' ' '`
			for x in `echo $p`
			do
				echo "	$x [shape=Mdiamond];" >> $OUTPUT
				echo "	$i -> $x;" >> $OUTPUT #  [label=\"provides\"];"
				#echo "	$x -> plugin;" >> $OUTPUT  # [label=\"is a\"];"
			done
		#else
			#echo "	$i -> plugin;" >> $OUTPUT  # [label=\"is a\"];"
		fi
	fi
done
echo "}"  >> $OUTPUT

echo >> $OUTPUT

fdp -Tpng $OUTPUT -o $SOURCE/doc/images/plugins.png
