#!/bin/sh
#
# @author Kurt Micheli <kurt.micheli@libelektra.org>
# @brief Draws a graph out of the opmphm output (opmphmGraph.dot)
# @date 25.11.2016
# @tags generator, creator

if [ -z "$1" ]
then
	echo "Usage $0 <dotfile>"
	exit
fi
outfile="$(echo "$1" | cut -d "." -f1-).png"
dot -Tpng "$1" -o "$outfile"
