#!/bin/sh

printf "name: "
ls $*

printf "size: "
ls -l $* | awk '{print $5;}'

printf "md5sum: "
md5sum $* | awk '{print $1;}'

printf "sha1: "
sha1sum $* | awk '{print $1;}'

printf "sha256: "
sha256sum $* | awk '{print $1;}'
