#!/bin/sh
#
# @tags release

# This script generates the required fields for NEWS.md entries
# and fill them with useful information
# e.g. the news id should be a UUID and the pubdate must be RFC822 conform

export LANG="C"
export LC_ALL="C"

echo - guid: $(uuidgen)
echo - author: Markus Raab
echo - pubDate: $(date +"%a, %d %b %Y %T %z")
echo - shortDesc:
