#!/bin/sh

echo -n "- name: "
basename "$*"

echo -n "- size: "
ls -l "$*" | cut -f 5 -d " "

echo -n "- md5sum: "
md5sum "$*" | cut -f 1 -d " "

echo -n "- sha1: "
sha1sum "$*" | cut -f 1 -d " "

echo -n "- sha256: "
sha256sum "$*" | cut -f 1 -d " " | head -c -1
