#!/bin/sh
#
# @tags release

echo -n "Number commits: "
git log $1..master | grep "^commit" | wc -l

git log $1..master | grep "^Author: " | sort | uniq -c | sort -n | sed 's/é/é/'

git diff $1..master --stat | tail -1
