#!/usr/bin/env sh
#
# @author René Schwaiger <sanssecours@me.com>
# @brief Checkouts ronn files
# @date 19.06.2018
# @tags helper, development

for file in $(git ls-files -m); do
	if echo "$file" | egrep -q '\.[17]$' && \
		test $(git diff --numstat "$file" | cut -f1) -le 1 && \
		git diff "$file" | grep -q '^-.TH'; then
		git checkout "$file"
	fi
done
