#!/bin/bash
#
# kdbd:   Starts the Elektra Key Database Daemon
#
# chkconfig: 12345 00 99
# description:  This is the overall daemon needed to correctly access Elektra
#               key databases on backends like BerkeleyDB.
#               The daemon will use the backend pointed
#               by /lib/elektra/libelektra-ddefault.so.
#               Though not recomended, an elektrified program can access a
#               key database without this daemon. But different permissions
#               calculations will be performed.
# processname: /sbin/kdbd
# config: 
# config: 
#
### BEGIN INIT INFO
# Provides: kdbd
# Required-Start: 
# Default-Stop: 0 6
# Short-Description: Starts the Elektra Key Database access daemon
# Description:  This is the overall daemon needed to correctly access Elektra
#               key databases on backends like BerkeleyDB.
#               The daemon will use the backend pointed
#               by /lib/elektra/libelektra-ddefault.so.
#               Though not recomended, an elektrified program can access a
#               key database without this daemon. But different permissions
#               calculations will be performed.
### END INIT INFO
#
# $Id$
#
#


KDBD_PATH=/sbin
RETVAL=0
prog=kdbd
pidfile=/var/run/kdbd/$prog.pid

# Sanity checks.
#[ -f /etc/nscd.conf ] || exit 0
[ -x $KDBD_PATH/kdbd ] || exit 0

# Source function library.
. /etc/init.d/functions

# Source an auxiliary options file if we have one, and pick up NSCD_OPTIONS.
#[ -r /etc/sysconfig/nscd ] && . /etc/sysconfig/nscd

start () {
	[ -d /var/run/$prog ] || mkdir /var/run/$prog
#    [ -d /var/db/nscd ] || mkdir /var/db/nscd
#    secure=""
	echo -n $"Starting $prog: "
	daemon $KDBD_PATH/$prog     # $secure $KDBD_OPTIONS
#	daemon --check $prog $prog --pidfile=$pidfile
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/kdbd
	return $RETVAL
}

stop () {
	echo -n $"Stopping $prog: "
	killproc $prog
	RETVAL=$?
	if [ $RETVAL -eq 0 ]; then
		rm -f /var/lock/subsys/$prog
		# nscd won't be able to remove these if it is running as
		# a non-privileged user
		rm -f /var/run/kdbd/$prog.pid
		rm -f /var/run/kdbd/elektra.sock
		success $"$prog shutdown"
	else
		failure $"$prog shutdown"
	fi
	echo
	return $RETVAL
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
	start)
	start
	RETVAL=$?
	;;
	stop)
	stop
	RETVAL=$?
	;;
    status)
	status kdbd
	RETVAL=$?
	;;
	restart)
	restart
	RETVAL=$?
	;;
	try-restart | condrestart)
	[ -e /var/lock/subsys/$prog ] && restart
	RETVAL=$?
	;;
	force-reload | reload)
	echo -n $"Reloading $prog: "
	killproc /usr/sbin/$prog -HUP
	RETVAL=$?
	echo
	;;
	*)
	echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
	RETVAL=1
	;;
esac
exit $RETVAL
