#!/bin/sh

if [ -z "$KDB" ]; then
	KDB=kdb
fi

if [ -z "$1" ]; then
	MOUNTPOINT=system/info
else
	MOUNTPOINT="$1"
fi

$KDB mount --resolver noresolver none $MOUNTPOINT/constants constants
$KDB mount --resolver noresolver none $MOUNTPOINT/uname uname
$KDB mount --resolver noresolver none $MOUNTPOINT/desktop desktop

