#!/bin/sh
#
# @author Markus Raab <elektra@markus-raab.org>
# @desc Mounts all config files from .kde/share/config
# @date 08.11.2014
# @tags mount
# @system kde

if [ -z "$KDB" ]; then
	KDB=kdb
fi

cd ~

for file in `find .kde/share/config -name '*rc' -type f`
do
	f=`basename $file rc`
	$KDB mount /$file user/org/kde/$f ni
done
