#!/bin/sh
#
# @tags mount

if [ -z "$KDB" ]; then
	KDB=kdb
fi

$KDB mount --resolver=resolver_fm_xhp_x color/settings/openicc.json /org/freedesktop/openicc yajl rename cut=org/freedesktop/openicc dbus announce=once
