#!/bin/sh
#
# @author Markus Raab <elektra@markus-raab.org>
# @desc Reformats the whole source code
# @date 18.02.2016
# @tags reformat
# @system all

SELF=$(readlink -f "$0")
SCRIPTS=$(dirname "$SELF")
SOURCE=$(dirname "$SCRIPTS")

cd $SOURCE

clang-format-3.8 -style=file -i `find . -name '*.[ch]' -or -name '*.[ch]pp' -or -name '*.[ch].in' | egrep -v "^(./src/tools/gen|./tests/gtest-1.7.0)"`
