#!/bin/sh
#
# @author Markus Raab <markus@libelektra.org>
# @brief Resets all keys in the key database
# @date 02.08.2019
# @tags umount, stash, helper

if [ -z "$KDB" ]; then
	KDB=kdb
fi

fail() {
	echo "$*" 2> /dev/null
	exit 1
}

if [ "$1" != "-f" ]; then
	fail "This is a very dangerous operation, read the man page first"
fi

KDBSYSTEM=$("$KDB" file system)
KDBUSER=$("$KDB" file user)
KDBSPEC=$("$KDB" file spec)

"$KDB" reset-elektra -f

"$KDB" rm -r --without-elektra system || rm -f "$KDBSYSTEM"

"$KDB" rm -r user || rm -f "$KDBUSER"
"$KDB" rm -r spec || rm -f "$KDBSPEC"
