#!/bin/sh
#
# @author Markus Raab <markus@libelektra.org>
# @brief Resets all keys in the key database
# @date 02.08.2019
# @tags umount, stash, helper

if [ -z "$KDB" ]; then
	KDB=kdb
fi

fail() {
	echo "$*" 2> /dev/null
	exit 1
}

if [ "$1" != "-f" ]; then
	fail "This is a very dangerous operation, read the man page first"
fi

$KDB rm -r --without-elektra system

$KDB reset-elektra

$KDB rm -r user
$KDB rm -r spec
