#!/bin/sh

###########################################################################
##
## This is a /etc/profile.d script to set user environment and aliases
## based on Registry keys under 'user/env'.
##
## Bellow user/env there must be three priorities for environment
## variables:
##
##     user/env/env1
##     user/env/env2
##     user/env/env3
##
## You should distribute your environment variables according to their
## dependencies. For example, if we want to
## set PATH as $JAVA_HOME/bin:$PATH, we'll have to set
##
##     user/env/env1/JAVA_HOME
##     user/env/env2/PATH
##
## This way it is guaranteed that the variables under user/env/env1 are
## set beffore those under user/env/env2, and before those under
## user/env/env3
##
## The folder user/env/alias contains keys to define shell aliases.
## So user/env/alias/ls may contain 'ls -Fh', to set an alias to
## the 'ls' command.
##
## Avi Alkalay <avi at unix dot sh>
## April 2004
##


if [ -z "$RG" ]; then
	RG=rg
fi

FILE="/tmp/rgenv$$"

#set -vx

echo "Setting environment from Registry keys under 'user/env'"

echo "# Stage 1" >> $FILE
$RG ls user/env/env1 2>/dev/null | while read key; do
	var=`basename $key`
	val=`rg get $key`
	echo "export $var=\"$val\""
done >> $FILE

echo >> $FILE
echo "# Stage 2" >> $FILE
$RG ls user/env/env2 2>/dev/null | while read key; do
	var=`basename $key`
	val=`rg get $key`
	echo "export $var=\"$val\""
done >> $FILE

echo >> $FILE
echo "# Stage 3" >> $FILE
$RG ls user/env/env3 2>/dev/null | while read key; do
	var=`basename $key`
	val=`rg get $key`
	echo "export $var=\"$val\"" 
done >> $FILE

echo >> $FILE
echo "# Aliases" >> $FILE
$RG ls user/env/alias 2>/dev/null | while read key; do
	var=`basename $key`
	val=`rg get $key`
	echo "alias $var=\"$val\"" 
done >> $FILE

. $FILE

rm -f $FILE
