#!/bin/sh

if [ $# -ne 1 ]
then
	echo "No build config. This script is supposed to run by using make run_nokdbtests"
	exit 1
fi

# run all tests not writing to disc

LD_LIBRARY_PATH=`pwd`/lib ctest -LE kdbtests --force-new-ctest-process --output-on-failure --build-config $1
