#!/bin/bash

# =============
# = Functions =
# =============

cleanup() {
        printf '👋  Change back to original directory “%s”\n' "$CURRENT_DIR"
        cd "$CURRENT_DIR" || exit
}

# ========
# = Init =
# ========

CURRENT_DIR="$PWD"
SCRIPTS_DIR=$(dirname "$0")
. "$SCRIPTS_DIR/realpath"

ELEKTRA_DIR=`realpath "$SCRIPTS_DIR"/..`
BUILD_DIR="$ELEKTRA_DIR/build"
MANPAGES_INPUT_DIR="$BUILD_DIR/doc/help"
MANPAGES_OUTPUT_DIR="$ELEKTRA_DIR/doc/man"

command -v ronn >/dev/null 2>&1 || { printf 'Unable to locate ronn' >&2; exit 1; }
command -v make >/dev/null 2>&1 || { printf 'Unable to locate Make' >&2; exit 1; }
command -v cmake >/dev/null 2>&1 || { printf 'Unable to locate CMake' >&2; exit 1; }

mkdir -p "$BUILD_DIR" || { printf 'Unable to create “%s”' "$BUILD_DIR" >&2; exit 1; }

# ========
# = Main =
# ========

printf '👋  Change into build directory “%s”\n' "$BUILD_DIR"
cd "$BUILD_DIR" || exit

printf '🔍  Run CMake\n'
cmake -DBUILD_DOCUMENTATION=ON -DTOOLS='ALL' -DBINDINGS='ALL' -DPLUGINS='ALL' ..

printf '📙  Build Elektra and its documentation\n'
make -j9 || ninja || { printf 'Unable to build Elektra' >&2; cleanup; exit 1; }

printf '📑  Copy man pages\n'
mkdir -p "$MANPAGES_OUTPUT_DIR" || { printf 'Unable to create “%s”' "$MANPAGES_OUTPUT_DIR" >&2; cleanup; exit 1; }
find -E "$MANPAGES_INPUT_DIR" -regex '.+\.[0-9]$' -exec cp '{}' "$MANPAGES_OUTPUT_DIR" \;

cleanup
