.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "ELEKTRA\-MERGE\-STRATEGIES" "7" "May 2023" ""
.SH "NAME"
\fBelektra\-merge\-strategies\fR \- how to merge key sets
.P
Elektra's merge library offers different strategies to resolve conflicts in merges without user interaction\. Consequently, Elektra's tools all have access to the following merge strategies:
.IP "\(bu" 4
\fBabort\fR: the merge will abort if any conflict happens and merge the 3 key sets together otherwise\.
.IP "\(bu" 4
\fBour\fR: This option forces conflicting keys to be auto\-resolved cleanly by favoring \fBour\fR\. Changes from the other key sets that do not conflict with the \fBour\fR version are reflected in the merge result\. This works like the recursive merge strategy with the \fBours\fR option of git\.
.IP "\(bu" 4
\fBtheir\fR: This is the opposite of \fBour\fR\. The merge will use the \fBtheir\fR version when a conflict happens\.
.IP "" 0
.P
If no strategy is specified, the merge will default to the abort strategy\.
