.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ELEKTRA\-SYNC\-FLAG" "7" "May 2020" "" ""
.
.SH "NAME"
\fBelektra\-sync\-flag\fR \- detection for writing
.
.P
Elektra keeps track of changes the user makes on data structures\. Because the \fBKeySet\fR can be composed in the way the user wants it, the \fBKeySet\fR does not give enough information if changes occurred within\. Instead, changes will be marked in individual \fBKey\fR objects\. On modifying functions, the so\-called \fBsync flag\fR will be set\.
.
.P
See also \fBkeyNeedSync()\fR\.
