.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "ELEKTRA\-NAMESPACES" "7" "November 2021" ""
.SH "NAME"
\fBelektra\-namespaces\fR \- namespaces
.SH "INTRODUCTION"
Every key in Elektra needs a unique name so that administrators can refer to them unambiguously\. Sometimes, multiple keys denote the same configuration item from different sources, e\.g\.:
.IP "\(bu" 4
by a commandline argument
.IP "\(bu" 4
by a configuration file found relative to the current directory
.IP "\(bu" 4
by a configuration file found relative to the home directory
.IP "\(bu" 4
by a configuration file found below \fB/\fR etc
.IP "" 0
.P
To allow such keys to exist in parallel, Elektra uses namespaces\.
.P
A namespace has the following properties:
.IP "\(bu" 4
in\-memory Keys start with one of the namespaces
.IP "\(bu" 4
keys within a namespace are known to stem from a specific configuration source\. For example files from the \fBuser\fR namespace are from the users home directory, \fBeven if\fR an absolute configuration file name was used\.
.IP "\(bu" 4
\fBksLookup()\fR uses multiple namespaces in a specific default order unless specified otherwise (cascading lookup)
.IP "" 0
.P
Following parts of Elektra source code are affected by namespaces:
.IP "\(bu" 4
the key name validation in \fBkeySetName()\fR
.IP "\(bu" 4
\fBkeyGetNamespace()\fR which enumerates all namespaces
.IP "\(bu" 4
\fB_Backend\fR and \fBsplit\.c\fR for correct distribution to plugins (note that not all namespaces actually are distributed to configuration files)
.IP "\(bu" 4
\fBmount\.c\fR for cascading and root backends
.IP "\(bu" 4
and of course many unit tests
.IP "" 0
.P
In the rest of this document all currently available namespaces in the default order are described\.
.SH "spec"
Unlike the other namespaces, the specification namespace does not contain values of the keys, but instead metadata as described in \fBMETADATA\.ini\fR \fI/doc/METADATA\.ini\fR\.
.P
When a cascading key is looked up, keys from the spec\-namespace are the first to be searched\. When a spec\-key is found, the rest of the lookup will be done as specified, probably in a different order than the namespaces enlisted here\.
.P
Usually, the spec\-keys do not directly contribute to the value, with one notable exception: the default value (metadata \fBdefault\fR, see in cascading below) might be used if every other way as specified in the spec\-key failed\.
.P
Spec\-keys typically include an explanation and description for the key itself (but not comments which are specific for individual keys)\.
.P
The spec configuration files are below \fBCMAKE_INSTALL_PREFIX/KDB_DB_SPEC\fR\.
.P
spec is not part of cascading mounts, because the specifications often are written in different syntax than the configuration files\.
.SH "proc"
Derived from the process (e\.g\. by parsing \fB/proc/self\fR or by arguments passed from the main method):
.IP "\(bu" 4
program name
.IP "\(bu" 4
arguments
.IP "\(bu" 4
environment
.IP "" 0
.P
Keys in the namespace proc can not be stored by their nature\. Thus they are ignored by \fBkdbGet\fR and \fBkdbSet\fR\. They might be different for every invocation of an application\.
.SH "dir"
Keys from the namespace \fBdir\fR are derived from a directory special to the user starting/using the application, e\.g\.:
.IP "\(bu" 4
the current working directory for project specific settings, e\.g\. \fB\.git\fR
.IP "\(bu" 4
the directory a server wants to present to the user, e\.g\. \fB\.htaccess\fR
.IP "" 0
.P
Note that Elektra only supports a single special directory per KDB instance\. Start a new KDB instance if you need different special directories for different parts of your application\. How to change the directory may be different dependent on the resolver, e\.g\. by using chdir or by setting the environment variable \fBPWD\fR\.
.SH "user"
On multi\-user operating systems obviously every user wants her/his own configuration\. The user configuration is located in the users home directory typically below the folder \fBKDB_DB_USER\.\fR Other paths below the home directory are possible too (absolute path for resolver)\.
.P
Note that Elektra only supports a user directory per KDB instance\. Start a new KDB instance if you need different user configuration for different parts of your application\. How to change the user may be different dependent on the resolver, e\.g\. by \fBseteuid()\fR or by environment variables like \fBHOME\fR, \fBUSER\fR
.SH "system"
The system configuration is the same for every chroot\.
.P
The configuration is typically located below \fBKDB_DB_SYSTEM\fR\. Other absolute paths, e\.g\. below \fB/opt\fR or \fB/usr/local/etc\fR are possible too\.
.SH "Cascading"
Keys that are not in a namespace (i\.e\. start with an \fB/\fR) are called cascading keys\. Cascading keys do not stem from a configuration source, but are used by applications to lookup a key in different namespaces\. So, multiple keys can contribute to each cascading key name\.
.P
Cascading is the same as a name resolution and provides a namespace unification as described in Versatility and Unix semantics in namespace unification \fIhttps://dl\.acm\.org/doi/10\.1145/1138041\.1138045\fR\.
.P
Keys without a namespace can not be stored by their nature\. So they are transient: after a restart they are forgotten\.
.P
Keys of that namespace are only used by ksLookup when no other suitable key was found\. So they have the lowest possible priority, even fallback keys are preferred\.
.P
Read more about cascading\. \fI/doc/help/elektra\-cascading\.md\fR
