.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre1
.TH "ELEKTRA\-VALUES" "7" "February 2019" ""
.SH "NAME"
\fBelektra\-values\fR \- values of elektra keys
.P
In Elektra string\-keys are preferred\. Nevertheless, binary keys, i\.e\. strings with null\-characters embedded are possible\.
.SH "ABSENT KEYS"
Sometimes a key does not exist at all\. When using ksLookup() you will get a null pointer\. In the C++ Binding the null pointer is wrapped in a key\. Thus this is also sometimes called \fBNULL KEYS\fR\.
.SH "NULL VALUES"
Null values are binary values without content\. They are the only keys that have the size 0\.
.P
Null values are always binary values\.
.SH "EMPTY VALUES"
Empty values point to a string that only contains a null byte\.
.P
Empty values are possible for both string and binary values\.
