.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre1
.TH "ELEKTRA\-LIBS" "7" "July 2022" ""
.SH "NAME"
\fBelektra\-libs\fR \- libs overview
.IP "" 4
\fBNote:\fR Some information in this document is outdated and will change before the release of Elektra 1\.0\.
.IP "" 0
.SH "Highlevel APIs"
.SS "Highlevel"
.nf
libelektra\-highlevel\.so
.fi
.P
Contains the \fBhighlevel API \fIhighlevel\fR\fR\. See also examples \fI/examples/highlevel\fR\.
.SS "Notification"
.nf
libelektra\-notification\.so
.fi
.P
\fBnotification \fInotification/\fR\fR provides the notification API \fIhttps://doc\.libelektra\.org/api/latest/html/group__kdbnotification\.html\fR\. Usage examples:
.IP "\(bu" 4
Basic notifications using polling \fIhttps://www\.libelektra\.org/examples/notificationpolling\fR
.IP "\(bu" 4
Using asynchronous I/O bindings \fIhttps://www\.libelektra\.org/examples/notificationasync\fR
.IP "\(bu" 4
Reload KDB when Elektra's configuration has changed \fIhttps://www\.libelektra\.org/examples/notificationreload\fR
.IP "" 0
.SH "Base Elektra Libraries"
Since version \fB0\.8\.15\fR \fBlibelektra \fIelektra/\fR\fR is split into following libraries:
.P
.SS "Libkdb"
.nf
libelektra\-kdb\.so
.fi
.P
Accesses the configuration files by orchestrating the plugins\. The implementation lives in \fIelektra\fR\.
.P
It coordinates the interactions between the applications and the plugins\.
.P
\fBloader \fIloader/\fR\fR contains source files that implement the plugin loader functionality as used by \fBlibelektra\-kdb\fR\.
.SS "Libcore"
.nf
libelektra\-core\.so
<kdbhelper\.h>
<kdb\.h> (key* and ks*)
.fi
.P
Contains the fundamental data\-structures every participant of Elektra needs to link against\. It should be the only part that access the internal data structures\. The implementation lives in \fIelektra\fR\.
.SS "Libease"
.nf
libelektra\-ease\.so
.fi
.P
\fBlibease \fIease/\fR\fR contains data\-structure operations on top of libcore which do not depend on internals\. Applications and plugins can choose to not link against it if they want to stay minimal\. Its main goal is to make programming with Elektra easier if some extra kB are not an issue\.
.SS "Libplugin"
.nf
libelektra\-plugin\.so
.fi
.P
\fBlibplugin \fIplugin/\fR\fR contains \fBelektraPlugin*\fR symbols to be used by plugins\.
.SS "Libmeta"
.nf
libelektra\-meta\.so
.fi
.P
\fBlibmeta \fImeta/meta\.c\fR\fR contains metadata operations as described in \fBMETADATA\.ini \fI/doc/METADATA\.ini\fR\fR\. Currently mainly contains legacy code and some generic metadata operations\.
.SS "Libelektra"
Is a legacy library that provides the same functionality as \fBlibelektra\-kdb\fR and \fBlibelektra\-core\fR\. The sources can be found in \fBlibelektra \fIelektra/\fR\fR\.
.SH "Other Libraries"
.SS "Libpluginprocess"
.nf
libelektra\-pluginprocess\.so
.fi
.P
\fBlibpluginprocess \fIpluginprocess/\fR\fR contains functions aiding in executing plugins in a separate process and communicating with those child processes\. This child process is forked from Elektra's main process each time such plugin is used and gets closed again afterwards\. It uses a simple communication protocol based on a KeySet that gets serialized through a pipe via the dump plugin to orchestrate the processes\.
.P
This is useful for plugins which cause memory leaks to be isolated in an own process\. Furthermore this is useful for runtimes or libraries that cannot be reinitialized in the same process after they have been used\.
.SS "Libtools"
\fBlibtools \fItools/\fR\fR is a high\-level C++ shared\-code for tools\. It includes:
.IP "\(bu" 4
plugin interface
.IP "\(bu" 4
backend interface
.IP "\(bu" 4
3\-way merge
.IP "" 0
.SS "Utility"
\fBlibutility \fIutility/\fR\fR provides utility functions to be used in plugins\.
.SS "Libinvoke"
.nf
libelektra\-invoke\.so
.fi
.P
\fBlibinvoke \fIinvoke/\fR\fR provides a simple API allowing us to call functions exported by plugins\.
.SS "IO"
.nf
libelektra\-io\.so
.fi
.P
\fBio \fIio/\fR\fR provides the common API \fIhttps://doc\.libelektra\.org/api/latest/html/group__kdbio\.html\fR for using asynchronous I/O bindings\.
.SS "Globbing"
.nf
libelektra\-globbing\.so
.fi
.P
\fBglobbing \fIglobbing/\fR\fR provides globbing functionality for Elektra\.
.P
The supported syntax is a superset of the syntax used by \fBglob(7)\fR\. The following extensions are supported:
.IP "\(bu" 4
\fB#\fR, when used as \fB/#/\fR (or \fB/#"\fR at the end of the pattern), matches a valid array item
.IP "\(bu" 4
\fB_\fR is the exact opposite; it matches anything but a valid array item
.IP "\(bu" 4
if the pattern ends with \fB/__\fR, matching key names may contain arbitrary suffixes
.IP "" 0
.P
For more info take a look a the documentation of \fBelektraKeyGlob()\fR and \fBelektraKsGlob()\fR\.
