.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "ELEKTRA\-MOUNTING" "7" "February 2019" ""
.SH "NAME"
\fBelektra\-mounting\fR \- mounting
.P
\fBMounting\fR is the process of integrating a backend that reads and writes a specific configuration file into the global key database\. Mounting allows you to use different configuration files but also allows you to change the behavior of writing/reading keys to/from the global key database\. For example, you need to mount if you want to:
.IP "\(bu" 4
change the syntax of a configuration file,
.IP "\(bu" 4
log every change of a configuration file,
.IP "\(bu" 4
validate a configuration file on every access,
.IP "\(bu" 4
change the representation (e\.g\. the date\-format or booleans), and
.IP "\(bu" 4
everything else plugins \fI/src/plugins/README\.md\fR can do\.
.IP "" 0
.P
\fBMounting\fR allegorises a common technique for virtual file systems \fI/doc/BIGPICTURE\.md\fR\. File systems on different partitions or devices can be added to the currently accessible file system\. Mounting is typically used to access data from external media\. A more advanced use case presents mounting a file system that is optimised for specific purposes, for example, one that can handle many small files well\. Mounting also allows us to access data via network storage\. As a result, mounting of file systems has proved to be extremely successful\.
.P
Mounting in Elektra specifically allows us to map a part of the global key database to be handled by a different storage\. A difference to file systems is that key names express what file names express in a file system\. And instead of file systems writing to block devices, backends writing to key databases are mounted into the global key database\. Mounting allows multiple backends to deal with configuration at the same time\. Each of them is responsible for its own subtree of the global key database\.
.P
Mounting works for file systems only if the file system below is accessible and a directory exists at the mount point\. Elektra does not enforce such restrictions\.
.P
Note, that you cannot mount the same configuration file multiple times\. You can, however, use the specification to link between configuration items which gives an impression of a \fIbind mount\fR, i\.e\. having the same configuration values on multiple places\.
.SH "SEE ALSO"
.IP "\(bu" 4
See elektra\-glossary(7) \fIelektra\-glossary\.md\fR
.IP "\(bu" 4
More information about elektra\-backends(7) \fIelektra\-backends\.md\fR
.IP "\(bu" 4
The tool for mounting plugins is kdb\-mount(1) \fIkdb\-mount\.md\fR
.IP "\(bu" 4
Back to main page \fI/README\.md\fR if you started from there
.IP "" 0

