#compiler-settings
directiveStartToken = @
cheetahVarStartToken = $
#end compiler-settings
@from support.gen import *
.\" Template for man pages
.TH man 3 "08.02.2013" "1.0" "template man page"
.SH NAME
template - modify this text for man page
.SH SYNOPSIS
nuseradd [USERNAME]
.SH DESCRIPTION
modify this text for man page
.SH OPTIONS
@for $key, $info in $parameters.items()
@if $info.get('opt'):
@if $info.get('opt/long'):
.IP "-$info.get('opt'), --$info.get('opt/long')"
@else
.IP "-$info.get('opt')"
@end if
$info.get('explanation')
@if $info.get('default')

\fRDefault:\fP $info.get('default')
@end if
@if $info.get('rationale')

\fRRationale:\fP $info.get('rationale')
@end if
@end if
@end for
.SH SEE ALSO
cat(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Markus Raab <elektra@markus-raab.org>
