#!/bin/sh
#
# @author: Sebastian Bachmann
# @tags: build
#

set -e
set -x

VERSION="0.9.3"
BUILD_NUMBER="1"

[ -d tmpbuilddir ] && rm -rf tmpbuilddir
mkdir tmpbuilddir
cd tmpbuilddir

git clone https://github.com/ElektraInitiative/libelektra.git
cd libelektra

git tag -f "v$VERSION"

git checkout -b debian origin/debian
git merge --no-ff -m "merge v$VERSION" master

dch -l ".$BUILD_NUMBER" "auto build"

git commit -am "auto build $VERSION"

git archive --format=tar HEAD | gzip > ../elektra_v$VERSION.orig.tar.gz

dpkg-buildpackage
