#!/bin/sh
#
# @author Markus Raab <elektra@markus-raab.org>
# @brief Configure a musl build
# @date 02.09.2014
# @tags configure, debian

SCRIPTS_DIR=$(dirname "$0")
. "${SCRIPTS_DIR}/configure-common"

cd "$BUILD" || exit
# CFLAGS="-fPIC" LDFLAGS="-fPIC" CXXFLAGS="-fPIC"
CC=musl-gcc CXX=g++ cmake \
	-DINSTALL_BUILD_TOOLS=ON \
	-DBUILD_TESTING=OFF -DBUILD_FULL=OFF -DBUILD_STATIC=OFF \
	-DPLUGINS="ALL;-yajl;-journald;-crypto;-dbus;-dbusrecv;-xmltool;-curlget;-multifile" \
	-DBINDINGS="cpp" \
	-KDB_DEFAULT_STORAGE=ini \
	-DTARGET_PLUGIN_FOLDER="" \
	-DGTEST_ROOT="/usr/src/googletest/googletest" \
	"$@"
