#!/bin/sh
#
# @author Markus Raab <elektra@markus-raab.org>
# @brief Configure a debian build with optimizations
# @date 02.09.2014
# @tags configure, debian

SCRIPTS_DIR=$(dirname "$0")
. "${SCRIPTS_DIR}/configure-common"

cd $BUILD
cmake -DPLUGINS="ALL" \
	-DTOOLS="ALL" \
	-DBINDINGS="cpp;swig_python2;swig_python;jna" \
	-DGTEST_ROOT="/usr/src/googletest/googletest" \
	$*
