#!/bin/sh
#
# @author Markus Raab <elektra@markus-raab.org>
# @brief Configure a debian build with optimizations
# @date 02.09.2014
# @tags configure, debian

SCRIPTS_DIR=$(dirname "$0")
. "${SCRIPTS_DIR}/configure-common"

cd "$BUILD" || exit
cmake -DENABLE_OPTIMIZATIONS="OFF" \
	-DPLUGINS="ALL" \
	-DTOOLS="ALL" \
	-DBINDINGS="ALL;-ruby" \
	-DENABLE_DEBUG="ON" \
	-DENABLE_LOGGER="ON" \
	-DBUILD_DOCUMENTATION="OFF" \
	-DGTEST_ROOT="/usr/src/googletest/googletest" \
	"$@"
