#!/bin/sh
#
# @author Markus Raab <elektra@markus-raab.org>
# @brief Configure a debian build which uses INI as default
# @date 02.09.2014
# @tags configure, debian

SCRIPTS_DIR=$(dirname "$0")
. "${SCRIPTS_DIR}/configure-common"

cd "$BUILD" || exit
cmake -DKDB_DB_FILE="default.ini" \
	-DKDB_DB_INIT="elektra.ini" \
	-DKDB_DEFAULT_STORAGE="ini" \
	-DPLUGINS="ALL" \
	-DTOOLS="ALL" \
	-DBINDINGS="ALL;-ruby" \
	-DGTEST_ROOT="/usr/src/googletest/googletest" \
	"$@"
