#!/bin/sh
#
# @author Markus Raab <elektra@markus-raab.org>
# @brief Configure a debian build with optimizations
# @date 02.09.2014
# @tags configure, debian

# a variant where everything is in a home-directory
# below .config by default

SCRIPTS_DIR=$(dirname "$0")
. "${SCRIPTS_DIR}/configure-common"

cd "$BUILD" || exit
cmake -DKDB_DB_USER=".config/kdb/user" \
	-DKDB_DB_SYSTEM="~/.config/kdb/system" \
	-DKDB_DB_SPEC="~/.config/kdb/spec" \
	-DTOOLS="ALL" \
	-DBINDINGS="ALL" \
	-DGTEST_ROOT="/usr/src/googletest/googletest" \
	"$@"

#-DKDB_DB_SPEC="~/.config/kdb/spec" \ # see ##691
