#!/bin/sh
#
# @author Michael Tucek <michael@tucek.eu>
# @brief Reformat Java files (based on reformat-javascript by René Schwaiger <sanssecours@me.com>)
# @date 27.05.2021
# @tags reformat

SCRIPTS_DIR=$(dirname "$0")
. "${SCRIPTS_DIR}/include-common"

cd "$SOURCE" || {
	printf 'Unable to change into source directory'
	exit 1
}

if [ $# -gt 0 ]; then
	java_files=$(printf "%s\n" "$@" | grep -Ex '.*\.java?')
	[ -z "$java" ] && exit
else
	java=$(git ls-files '*.java')
fi
printf "%s\n" "$java" | sed -nE 's/(.*)/'"'"'\1'"'"'/p' | xargs prettier --parser java --use-tabs --write -- > /dev/null
