#!/bin/sh
#
# @author Michael Tucek <michael@tucek.eu>
# @brief Reformats Java source code
# @date 30.09.2021
# @tags reformat

FORMATTER_JAR=/tmp/google-java-format.jar
FORMATTER_DOWNLOAD_URL=https://github.com/google/google-java-format/releases/download/v1.11.0/google-java-format-1.11.0-all-deps.jar
if [ -f $FORMATTER_JAR ]; then
	echo "Using existing $FORMATTER_JAR"
else
	echo "Downloading $FORMATTER_DOWNLOAD_URL to $FORMATTER_JAR"
	curl -o $FORMATTER_JAR -L $FORMATTER_DOWNLOAD_URL
fi

SCRIPTS_DIR=$(dirname "$0")
. "${SCRIPTS_DIR}/include-common"

cd "$SOURCE" || {
	printf >&2 'Unable to change into source directory'
	exit 1
}

if [ $# -gt 0 ]; then
	source_files=$(printf "%s\n" "$@" | grep -x -E '.*\.java')
	if [ -z "$source_files" ]; then
		exit 0
	fi
else
	source_files=$(git ls-files '*.java')
fi
printf "%s\n" "$source_files" | sed -nE 's/(.*)/'"'"'\1'"'"'/p' | xargs java --illegal-access=permit -jar $FORMATTER_JAR --replace
