#!/bin/sh
#
# @author Klemens Böswirth <k.boeswirth+git@gmail.com>
# @brief Calls all other reformat scripts
# @date 29.03.2019
# @tags reformat

DEV_SCRIPTS_DIR=$(dirname "$0")
. "${DEV_SCRIPTS_DIR}/include-common"

cd "$SOURCE" || exit

reformat() {
	reformat=$1
	shift
	echo "starting $reformat ..."
	"$reformat" "$@"
	echo "finished $reformat"
}

for reformat in "$DEV_SCRIPTS_DIR"/reformat-*; do
	[ "$(basename "$reformat")" = "reformat-all" ] && continue
	reformat "$reformat" "$@" &
	PIDS="$PIDS $!"
done

for pid in $PIDS; do
	wait "$pid"
done
