#!/bin/sh
#
# @author René Schwaiger <sanssecours@me.com>
# @brief Reformat JavaScript files
# @date 13.10.2019
# @tags reformat

SCRIPTS_DIR=$(dirname "$0")
. "${SCRIPTS_DIR}/include-common"

cd "$SOURCE" || {
	printf 'Unable to change into source directory'
	exit 1
}

if [ $# -gt 0 ]; then
	javascript_files=$(printf "%s\n" "$@" | grep -Ex '.*\.jsx?')
	[ -z "$javascript_files" ] && exit
else
	# The file `TooltipCreator.js` contains the text `.pragma library`, which is not valid JavaScript code.
	javascript_files=$(git ls-files '*.js' '*.jsx' | grep -v 'src/tools/qt-gui/qml/TooltipCreator.js')
fi
printf "%s\n" "$javascript_files" | sed -nE 's/(.*)/'"'"'\1'"'"'/p' | xargs prettier --trailing-comma none --write -- > /dev/null
