#!/bin/sh
#
# @author Klemens Böswirth <k.boeswirth+git@gmail.com>
# @brief Calls all other reformat scripts
# @date 29.03.2019
# @tags reformat

DEV_SCRIPTS_DIR=$(dirname "$0")
. "${DEV_SCRIPTS_DIR}/include-common"

cd "$SOURCE"

OLD_IFS="$IFS"
IFS='
'
for reformat in $(ls "$DEV_SCRIPTS_DIR"/reformat-*); do
	[ "$(basename "$reformat")" = "reformat-all" ] && continue
	echo "running $reformat..."
	"$reformat" "$@"
done
IFS="$OLD_IFS"
