#!/usr/bin/zsh
# To be used in .zshrc, shebang exists to supress checkbashisms warning

alias kdb='nocorrect noglob kdb'
alias bin/kdb='nocorrect noglob bin/kdb'
alias kdb-full='nocorrect noglob kdb-full'
alias bin/kdb-full='nocorrect noglob bin/kdb-full'
alias kdb-static='nocorrect noglob kdb-static'
alias bin/kdb-static='nocorrect noglob bin/kdb-static'
