#!/usr/bin/env bash

###########################################################################
##
## This script sets up basic bash completion for the kdb command
##
##
## Put it under /etc/bash_completion.d or load it just for the current
## session with . <scriptname>
##
###########################################################################

_kdb() {
	COMPREPLY=()
	local cur="${COMP_WORDS[COMP_CWORD]}"
	local cur_str=""
	if ! [ -z "${cur}" ]; then
		cur_str="-s ${cur}"
	fi
	in=" "
	for ((i = 1; i < COMP_CWORD; i++)); do
		in+=" ${COMP_WORDS[i]}"
	done
	output="$(python3 /home/jenkins/workspace/src/tools/autocompletion/src/autocompletion.py -m system:/spec/autocomplete/kdb ${cur_str} ${in})"
	COMPREPLY=($(compgen -W "${output}"))
}

# complete the command with _kdb and fall back to filename completion
complete -o default -F _kdb kdb
