.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "KDB\-VSET" "1" "August 2019" "" ""
.
.SH "NAME"
\fBkdb\-vset\fR \- Set the value of a key with a validation regular expression
.
.SH "SYNOPSIS"
\fBkdb vset <key name> <value> <regex> [<message>]\fR
.
.P
Where \fBkey name\fR is the name of the key the user wishes to set, \fBvalue\fR is the value the user wishes to set, and \fBregex\fR is the regular expression that should be used for validation\. The optional parameter \fBmessage\fR is a user\-defined message that will be displayed when a user tries to set the key to a value that doesn\'t match the regular expression\. The expression will be matched against the whole value (\fBcheck/validation/match=LINE\fR)\.
.
.SH "DESCRIPTION"
This command allows the user to set the value of a key and create a validation regular expression which future sets are checked against\. This command supports regular expressions as defined in extended regular expressions\. If a user tries to set a value that does not match the regular expression, a user\-defined message is returned\.
.
.P
Note: In order for this command to work, the \fBvalidation\fR plugin must be mounted where the key resides\.
.
.SH "OPTIONS"
.
.TP
\fB\-H\fR, \fB\-\-help\fR
Show the man page\.
.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info\.
.
.TP
\fB\-p\fR, \fB\-\-profile <profile>\fR
Use a different kdb profile\.
.
.TP
\fB\-C\fR, \fB\-\-color <when>\fR
Print never/auto(default)/always colored output\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Explain what is happening\. Prints additional information in case of errors/warnings\.
.
.TP
\fB\-d\fR, \fB\-\-debug\fR
Give debug information\. Prints additional debug information in case of errors/warnings\.
.
.SH "EXAMPLES"
To mount the necessary validation plugin use:
.
.br
\fBkdb mount validation\.ini /validation ini validation\fR
.
.P
To set the \fBuser/validation/key\fR key to the value \fBa\fR and validate that any future sets must match the regular expression \fBa+\fR:
.
.br
\fBkdb vset user/validation/key a a+ "The value of this key must only consist of one more of the letter a"\fR
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
Use \fBkdb plugin-info validation\fR to get information about the validation plugin\.
.
.IP "\(bu" 4
elektra\-key\-names(7) \fIelektra\-key\-names\.md\fR for an explanation of key names\.
.
.IP "" 0

