.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "README" "" "October 2022" ""
.SH "Introduction"
The tool \fBqt\-gui\fR offers a graphical interface for users of Elektra\. It allows users to create, manage, edit, and delete keys stored in the global key database (KDB)\.
.SH "Compiling and Installation"
.SS "Dependencies"
In order to compile and use the new \fBqt\-gui\fR there are a few dependencies which must be installed\.
.IP "\(bu" 4
qt5\.3 or greater
.IP "\(bu" 4
libdrm\-dev
.IP "\(bu" 4
libdiscount (libmarkdown2\-dev)
.IP "\(bu" 4
the following qt5 modules: \fBquickcontrols\fR \fBdeclarative\fR (\fBqtdeclarative5\-dev\fR)
.IP "\(bu" 4
Alternatively, you may need \fBsudo apt\-get install qml\-module\-qt\-labs\-folderlistmodel\fR and \fBsudo apt\-get install qml\-module\-qt\-labs\-settings\fR
.IP "" 0
.P
Optional dependencies are (are automatically deactivated if dependencies are not found):
.IP "\(bu" 4
\fBQt5Svg\fR for SVG icon themes (\fBsudo apt\-get install libqt5svg5\-dev\fR)
.IP "\(bu" 4
\fBQt5DBus\fR so that \fBqt\-gui\fR will be notified on changes\.
.IP "" 0
.P
On Ubuntu (tested on 14\.10 and 20\.04) you can install the dependencies with
.IP "" 4
.nf
sudo apt\-get install \e
    qt5\-default \e
    qml\-module\-qtquick\-controls \e
    qml\-module\-qtquick\-dialogs \e
    qml\-module\-qtquick\-layouts \e
    qml\-module\-qtgraphicaleffects \e
    libdrm\-dev \e
    libmarkdown2\-dev \e
    libqt5svg5\-dev
.fi
.IP "" 0
.SS "Change Notification"
It is recommended to use the viewer mode if DBus notifications are expected\. Use "Settings \-> Viewermode" to activate the viewermode\.
.P
To publish changes to KDB via DBus use:
.P
\fBkdb global\-mount dbus\fR
.P
\fBqt\-gui\fR also subscribes to DBus notifications and automatically synchronizes the configuration when notified\.
.P
Known Issue: On reload the current element in the tree view gets unselected, you need to click on the element of interest again\.
.SS "Compiling"
Compile Elektra as normal as per the COMPILE document \fI/doc/COMPILE\.md\fR making sure to include the \fBqt\-gui\fR tool using the \fB\-DTOOLS\fR flag\.
.P
For instance: \fB\-DTOOLS=ALL\fR or \fB\-DTOOLS=qt\-gui\fR
.P
Note: If you install qt5 manually, you must either:
.IP "\(bu" 4
make sure the qt5 libraries are included in \fBLD_LIBRARY_PATH\fR
.IP "\(bu" 4
OR make sure to specify \fB\-DCMAKE_PREFIX_PATH=/opt/Qt5\.3\.0/5\.3/gcc_64/lib/cmake\fR
.IP "" 0
.SS "Installing"
You can now install Elektra as you normally would or as described in the install documentation \fI/doc/INSTALL\.md\fR\. The package is called \fBelektra\-qt\-gui\fR\.
.SH "To Run"
The following command will launch the Qt\-GUI:
.IP "" 4
.nf
kdb qt\-gui
.fi
.IP "" 0
.P
After that a window will open that looks something like that:
.P
.P
You can mount a backend by going to \fIDatabase\fR \-\-> \fIMount Backend\|\.\|\.\|\.\fR
.P
.P
This will open the mounting wizard where you can add a path:
.P
.P
Next you can browse through the available backends and read their documentation\.
.P
.P
After you are done reading the documentation you can close the window again\.
.P
If you want to add a new key to the database you can choose a namespace in the left panel then click on Edit \-\-> New \-\-> Key\. This will open a new window that looks like this:
.P
.P
After entering the key information, you can view it in the list view\. Just click on the namespace you chose and select the key\.
.P

