.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-BASENAME" "1" "September 2022" ""
.SH "NAME"
\fBkdb\-basename\fR \- Get the basename of a key name
.SH "SYNOPSIS"
\fBkdb basename <key name>\fR
.P
Where \fBkey name\fR is the name of the key\.
.SH "DESCRIPTION"
This command is used to retrieve the basename of a key\.
.SH "RETURN VALUES"
This command will return the following values as an exit status:
.TP
0
No errors\.
.TP
1\-10
standard exit codes, see kdb(1) \fIkdb\.md\fR
.TP
11
invalid key name passed
.SH "OPTIONS"
.TP
\fB\-n\fR, \fB\-\-no\-newline\fR
Suppress the newline at the end of the output\.
.SH "EXAMPLES"
.nf
kdb basename user:/key/subkey
#> subkey

kdb basename user:/key/subkey/
#> subkey

kdb basename /
#>
.fi
.SH "SEE ALSO"
.IP "\(bu" 4
See kdb\-namespace(1) \fIkdb\-namespace\.md\fR and kdb\-dirname(1) \fIkdb\-dirname\.md\fR for other namepart extraction operations\.
.IP "\(bu" 4
The Unix analogue [BASENAME(1)]\.
.IP "\(bu" 4
To get keys in shell scripts, you can use kdb\-sget(1) \fIkdb\-sget\.md\fR\.
.IP "\(bu" 4
elektra\-key\-names(7) \fIelektra\-key\-names\.md\fR for an explanation of key names\.
.IP "" 0

