.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-RECORD\-EXPORT" "1" "May 2023" ""
.SH "NAME"
\fBkdb\-record\-export\fR \- Export recorded changes
.SH "SYNOPSIS"
\fBkdb record\-export [<source>] [<format>]\fR
.br
.SH "DESCRIPTION"
This command exports the recorded changes into the specified output format\. Keys are exported to \fBstdout\fR in whichever format is specified\.
.SH "USAGE"
Where \fBsource\fR is the path of the key(s) you want to export\. Additionally, the user can specify a format to use by passing it as the option argument \fBformat\fR\. The \fBformat\fR attribute relies on Elektra’s plugin system to export the keys in the desired format\. The parameter \fBformat\fR must be the name of a valid storage plugin\.
.P
Both \fBsource\fR and \fBformat\fR are optional parameters\. By default, \fBsource\fR is \fB/\fR and \fBformat\fR is \fBansible\fR\. If you only specify a single argument, we will whether it is a key or the format\.
.SH "OPTIONS"
.TP
\fB\-H\fR, \fB\-\-help\fR
Show the man page\.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info\.
.TP
\fB\-p\fR, \fB\-\-profile <profile>\fR
Use a different kdb profile\.
.TP
\fB\-C\fR, \fB\-\-color <when>\fR
Print never/auto(default)/always colored output\.
.TP
\fB\-E\fR, \fB\-\-without\-elektra\fR
Omit the \fBsystem:/elektra\fR directory\.
.TP
\fB\-S\fR, \fB\-\-include\-recording\-session\fR
Include the recording session in the output\.
.TP
\fB\-c\fR, \fB\-\-plugins\-config <plugins\-config>\fR
Add a configuration to the format plugin\.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Explain what is happening\. Prints additional information in case of errors/warnings\.
.TP
\fB\-d\fR, \fB\-\-debug\fR
Give debug information\. Prints additional debug information in case of errors/warnings\.
.SH "RETURN VALUE"
.TP
0
Successful\.
.TP
1\-10
standard exit codes, see kdb(1) \fIkdb\.md\fR\.
.TP
11
An error occurred during exporting\.
.SH "SEE ALSO"
.IP "\(bu" 4
kdb\-record\-start(1) \fIkdb\-record\-start\.md\fR on how to start the recording session
.IP "\(bu" 4
kdb\-record\-stop(1) \fIkdb\-record\-stop\.md\fR on how to stop the recording session
.IP "\(bu" 4
kdb\-record\-state(1) \fIkdb\-record\-state\.md\fR on how to get information about the current recording session
.IP "" 0

