.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-IMPORT" "1" "May 2023" ""
.SH "NAME"
\fBkdb\-import\fR \- Import an existing configuration into the key database
.SH "SYNOPSIS"
\fBkdb import <destination> [<format>]\fR
.P
Where \fBdestination\fR is the destination where the user wants the keys to be imported into\. \fBformat\fR is the format of the keys that are imported\.
.SH "DESCRIPTION"
If the \fBformat\fR argument is not passed, then the default format will be used as determined by the value of the \fBsw/kdb/current/format\fR key\. By default, that key is set to the \fBstorage\fR format\. The \fBformat\fR attribute relies on Elektra’s plugin system to properly import the configuration\. The user can view all plugins available for use by running the kdb\-plugin\-list(1) command\. To learn about any plugin, the user can simply use the kdb\-plugin\-info(1) command\.
.P
This command allows a user to import an existing configuration into the key database\. The configuration that the user wants to import is read from \fBstdin\fR\. The user should specify the format that the current configuration or keys are in, otherwise the default format will be used\. The default format is \fBstorage\fR but can be changed by editing the value of the \fB/sw/elektra/kdb/#0/current/format\fR key\. The \fBstorage\fR plugin can be configured at compile\-time or changed by the link \fBlibelektra\-plugin\-storage\.so\fR\.
.SH "CONFLICTS"
Conflicts can occur when importing a configuration to a part of the database where keys already exist\. Conflicts when importing can be resolved using a strategy with the \fB\-s\fR argument\.
.P
The strategies implemented by the merge framework are documented in elektra\-merge\-strategy(7) \fIelektra\-merge\-strategy\.md\fR\.
.SH "OPTIONS"
.TP
\fB\-H\fR, \fB\-\-help\fR
Show the man page\.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info\.
.TP
\fB\-p\fR, \fB\-\-profile <profile>\fR
Use a different kdb profile\.
.TP
\fB\-C\fR, \fB\-\-color <when>\fR
Print never/auto(default)/always colored output\.
.TP
\fB\-s\fR, \fB\-\-strategy <name>\fR
Specify which strategy should be used to resolve conflicts\.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Explain what is happening\. Prints additional information in case of errors/warnings\.
.TP
\fB\-d\fR, \fB\-\-debug\fR
Give debug information\. Prints additional debug information in case of errors/warnings\.
.TP
\fB\-c\fR, \fB\-\-plugins\-config\fR
Add a configuration to the format plugin\.
.SH "KDB"
.IP "\(bu" 4
\fB/sw/elektra/kdb/#0/current/verbose\fR: Same as \fB\-v\fR: Explain what is happening (output merged keys)\.
.IP "\(bu" 4
\fB/sw/elektra/kdb/#0/current/format\fR Change default format (if none is given at commandline) and built\-in default is not your preferred format\.
.IP "" 0
.SH "EXAMPLES"
To import a configuration stored in the XML format in a file called \fBexample\.xml\fR below \fBuser:/keyset\fR:
.br
\fBkdb import user:/keyset xmltool < example\.xml\fR
.P
To import a configuration stored in the \fBini\fR format in a file called \fBexample\.ini\fR below \fBuser:/keyset\fR replacing any previous keys stored there:
.br
\fBcat example\.ini | kdb import \-s cut user:/keyset ini\fR
.P
To import a configuration stored in the \fBini\fR format in a file called \fBexample\.ini\fR below \fBuser:/keyset\fR keeping any previous keys stored there that aren't present in the newly imported configuration:
.br
\fBcat example\.ini | kdb import \-s import user:/keyset ini\fR
.P
To restore a backup (stored as \fBsw\.ecf\fR) of a user's configuration below \fBsystem:/sw\fR:
.br
\fBcat sw\.ecf | kdb import system:/sw\fR
.P
To import a sample \fBxml\fR content with the \fBxerces\fR plugin:
.IP "" 4
.nf
# import two keys from a xml string
kdb import user:/tests/kdb\-import/ xerces <<< "<?xml version=\e"1\.0\e" encoding=\e"UTF\-8\e" standalone=\e"no\e" ?><kdb\-import><one>one</one><two>two</two></kdb\-import>"

# get the values and verify they got imported correctly
kdb get user:/tests/kdb\-import/one
#> one
kdb get user:/tests/kdb\-import/two
#> two
kdb rm \-r user:/tests/kdb\-import
.fi
.IP "" 0
.P
To import a sample \fBxml\fR content via specifying the file format directly:
.IP "" 4
.nf
# import two keys from a xml string
kdb import user:/tests/kdb\-import/ xml <<< "<?xml version=\e"1\.0\e" encoding=\e"UTF\-8\e" standalone=\e"no\e" ?><kdb\-import><one>one</one><two>two</two></kdb\-import>"

# get the values and verify they got imported correctly
kdb get user:/tests/kdb\-import/one
#> one
kdb get user:/tests/kdb\-import/two
#> two

kdb rm \-r user:/tests/kdb\-import
.fi
.IP "" 0
.SH "SEE ALSO"
.IP "\(bu" 4
elektra\-merge\-strategy(7) \fIelektra\-merge\-strategy\.md\fR
.IP "" 0

