.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-SHELL" "1" "May 2023" ""
.SH "NAME"
\fBkdb\-shell\fR \- Start a kdb shell instance
.SH "SYNOPSIS"
\fBkdb shell\fR
.SH "DESCRIPTION"
This command is used to start an instance of the kdb shell\.
.br
The kdb shell allows for a user to interactively view, edit, or otherwise work with the key database\.
.br
.SH "SHELL COMMANDS"
The kdb shell offers a number of commands to interact with the key database\.
.IP "\(bu" 4
\fBkdbGet <name>\fR: Get the value of a key\.
.IP "\(bu" 4
\fBkdbSet <name>\fR: Set the value of a key\.
.IP "\(bu" 4
\fBkeySetName <name>\fR: Set the name of the current key\.
.IP "\(bu" 4
\fBkeySetMeta <name> <string>\fR: Set a metakey associated with the current key\.
.IP "\(bu" 4
\fBkeySetString <string>\fR: Set a string value for the current key\.
.IP "\(bu" 4
\fBksAppendKey\fR: Append the current key to the current keyset\.
.IP "\(bu" 4
\fBksCut <name>\fR: Cut the current keyset\.
.IP "\(bu" 4
\fBksOutput\fR: Prints the keys in the current keyset\.
.IP "" 0
.SH "OPTIONS"
.TP
\fB\-H\fR, \fB\-\-help\fR
Show usage of command\.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info\.
.TP
\fB\-C\fR, \fB\-\-color <when>\fR
Print never/auto(default)/always colored output\.
.SH "EXAMPLES"
To execute commands from a textfile, you can use:
.br
\fBcat commands\.txt | kdb shell\fR
.P
To have readline functionality (line editing, history, \|\.\|\.\|\.), you can use:
.br
\fBrlwrap kdb shell\fR
.SH "SEE ALSO"
To learn more about these commands and how they work, refer to the Elektra API Documentation \fIhttps://doc\.libelektra\.org/api/latest/html\fR\.
