.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-FIND\-TOOLS" "1" "September 2019" ""
.SH "NAME"
\fBkdb\-find\-tools\fR \- The tool for finding tools
.SH "SYNOPSIS"
.nf
kdb find\-tools [\-h] [\-\-warnings] [\-\-good] [\-\-alltags] [\-n NAME] [\-a AUTHOR] [\-d DATE]
               [\-t TAGS [TAGS \|\.\|\.\|\.]] [\-b BRIEF] [\-e EXECUTE]
.fi
.SH "DESCRIPTION"
If you are looking for a tool, then you have found the right tool to find tools! \fBkdb find\-tools\fR provides search and list functionality for tools\.
.P
Just enter \fBkdb find\-tools\fR to get a list of names, type and short description of all available tools\.
.P
If you are looking for something special, then there are two ways:
.IP "1." 4
Tag Search: Type \fBkdb find\-tools \-\-alltags\fR to get a list of all Tags in use\. Then you can search with \fBkdb \-t [TAGS [TAGS \|\.\|\.\|\.]]\fR
.IP "2." 4
Full Text Search:
.IP "\(bu" 4
\fBkdb find\-tools \-n NAME\fR to search for a script name\.
.IP "\(bu" 4
\fBkdb find\-tools \-b BRIEF\fR to search for a short text\.
.IP "\(bu" 4
\fBkdb find\-tools \-a AUTHOR\fR to search for an author\.
.IP "\(bu" 4
\fBkdb find\-tools \-d DATE\fR to search for a creation date\.
.IP "\(bu" 4
\fBkdb find\-tools \-e EXECUTE\fR to search for a type\.
.IP "" 0

.IP "" 0
.P
All methods can be combined\. For example if you search all bash scripts which do some configuration work\. You can type \fBkdb find\-tools \-t configuration \-e bash\fR\.
.SH "The Right Way to Add Your Script to the Find Tools"
Meta Tags as comments in the beginning of a script are parsed\. Mate Tags start with an \fB@\fR, here is a list of all Meta Tags:
.TS
allbox;
l l.
MetaTag	Meaning
\e@author	Names and Emails (in <>) of the Authors as comma separated list
\e@brief	A Short Description (One Line!)
\e@tags	Comma Separated List of Tags
\e@date	Date when the script was created, use DD\.MM\.YYYY as format
.TE
.P
Do not mind the '' at the beginning it is a doxygen escaping\.
.P
Beware, that these metatags should be applied at the beginning of the file (in the first 10 rows)!
.SH "Example"
.nf
#!/bin/sh
#
# @author Kurt Micheli <kurt\.micheli@libelektra\.org>
# @brief This is an example of a build script
# @date 31\.10\.2018
# @tags configure, build
.fi
.SH "Notes"
The Metatag System of Epydoc is used (http://epydoc\.sourceforge\.net/manual\-fields\.html#module\-metadata\-variables) and extended with special tags\.
