.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-SGET" "1" "May 2023" ""
.SH "NAME"
\fBkdb\-sget\fR \- Get the value of a key stored in the key database from a script
.SH "SYNOPSIS"
\fBkdb sget <key name> <default\-value>\fR
.P
Where \fBkey name\fR is the name of the key to retrieve and \fBdefault\-value\fR is the value that should be printed if no value can be retrieved\.
.SH "DESCRIPTION"
This command is used to retrieve the value of a key from within a script\. When using the kdb tool in a script, the user should use the \fBsget\fR command in place of the kdb\-get(1) command\. The kdb\-get(1) command should not be used in scripts because it may return an error instead of printing a value in certain circumstances\. The \fBsget\fR command guarantees that a value will be printed (unless the user passes faulty arguments)\. This command will either print the value of the key it retrieves or a default value that the user specifies\.
.SH "OPTIONS"
.TP
\fB\-H\fR, \fB\-\-help\fR
Show usage of command\.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info\.
.TP
\fB\-C\fR, \fB\-\-color <when>\fR
Print never/auto(default)/always colored output\.
.SH "EXAMPLES"
To get the value of a key from a script or return the value \fB0\fR:
.br
\fBkdb sget user:/example/key 0\fR
.P
To get the value of a key using a cascading lookup or return the value \fBnotfound\fR:
.br
\fBkdb sget /example/key "notfound"\fR
.SH "SEE ALSO"
.IP "\(bu" 4
kdb\-get(1) \fIkdb\-get\.md\fR
.IP "\(bu" 4
elektra\-key\-names(7) \fIelektra\-key\-names\.md\fR for an explanation of key names\.
.IP "" 0

