.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-CONVERT" "1" "May 2023" ""
.SH "NAME"
\fBkdb\-convert\fR \- Convert configuration files using elektra
.SH "SYNOPSIS"
\fBkdb convert [<import\-format>] [<export\-format>] [<import\-file>] [export\-file]\fR
.SH "DESCRIPTION"
This command allows a user to convert a file from any format supported by Elektra to any other supported format\.
.P
This command relies on the functionality of Elektra but does not actually modify the key database in any way\.
.P
This command uses plugins to specify and convert between formats, it is only limited by the plugins available for Elektra\.
.SH "USAGE"
Where \fBimport\-format\fR is the format that the current configuration file is using, \fBexport\-format\fR is the format the user wishes to convert it to, \fBimport\-file\fR is the full path to the current configuration file, and \fBexport\-file\fR is where the converted configuration file should be saved\.
.P
If either \fBimport\-format\fR or \fBexport\-format\fR is not specified, the \fBstorage\fR plugin will be used instead\. The \fBstorage\fR plugin can be configured at compile\-time or changed by the link \fBlibelektra\-plugin\-storage\.so\fR\. If either \fBimport\-file\fR or \fBexport\-file\fR are not specified, \fBstdin\fR and \fBstdout\fR are used respectively\.
.SH "OPTIONS"
.TP
\fB\-H\fR, \fB\-\-help\fR
Show usage of command\.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info\.
.TP
\fB\-C\fR, \fB\-\-color <when>\fR
Print never/auto(default)/always colored output\.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Explain what is happening\. Prints additional information in case of errors/warnings\.
.TP
\fB\-d\fR, \fB\-\-debug\fR
Give debug information\. Prints additional debug information in case of errors/warnings\.
.SH "EXAMPLES"
To convert an Elektra dump file to xml:
.br
\fBcat sw\.ecf | kdb convert dump xmltool > sw\.xml\fR
.P
Another way to convert an Elektra dump file to xml:
.br
\fBkdb convert dump xmltool /home/user/dump_file\.ecf /home/user/xml_file\.xml\fR
.P
To print an xml file using the \fBline\fR format:
.br
\fBcat \.\./tests/xml_file\.xml | kdb convert xmltool line\fR
.br
Note that this command won't save the output, it will just display it to \fBstdout\fR\.
