.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-GEN" "1" "May 2023" ""
.SH "NAME"
\fBkdb\-gen\fR \- Elektra's code\-generator
.SH "SYNOPSIS"
\fBkdb gen <templateName> <parentKey> <outputName> [parameters\|\.\|\.\|\.]\fR
.TP
\fB<templateName>\fR
one of the templates listed \fIbelow\fR
.TP
\fB<parentKey>\fR
the parent key to use, templates may have certain restrictions on e\.g\. the allowed namespaces You may also use the special value \fB\-\fR (see below)\.
.TP
\fB<outputName>\fR
the base name of the output files\. If a template produces multiple files, it will append different suffixes (e\.g\. file extensions) to this base name\.
.TP
\fB[parameters\|\.\|\.\|\.]\fR
a list of parameters, the supported parameters depend on the template
.SH "DESCRIPTION"
This command invokes Elektra's code\-generator\.
.P
It supports different templates\. All templates require a \fBparentKey\fR parameter, because this determines the input for the code\-generator, as well as an \fBoutputName\fR parameter to specify the output file(s)\.
.P
If the given \fBparentKey\fR is \fB\-\fR, instead of actually invoking the code generator, \fBkdb gen\fR will just print the filenames of the files that would be written with a valid \fBparentKey\fR\.
.P
For more information see the \fIlist of templates\fR below and the man\-pages for each of them\.
.SH "RETURN VALUES"
This command will return the following values as an exit status:
.TP
0
No errors\.
.TP
1\-10
standard exit codes, see kdb(1) \fIkdb\.md\fR
.SH "OPTIONS"
.TP
\fB\-H\fR, \fB\-\-help\fR
Show usage of command\.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info\.
.TP
\fB\-C\fR, \fB\-\-color <when>\fR
Print never/auto(default)/always colored output\.
.TP
\fB\-F\fR, \fB\-\-input\-file <plugin>=<file>\fR
Load the file \fB<file>\fR with plugin \fB<plugin>\fR instead of accessing the KDB\.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Explain what is happening\. Gives a complete trace of all tried keys\. Very useful to debug fallback and overrides\.
.TP
\fB\-d\fR, \fB\-\-debug\fR
Give debug information\. Prints additional debug information in case of errors/warnings\.
.SH "TEMPLATES"
Currently we only have one template:
.TP
\fBhighlevel\fR
Generates the files needed for using the high\-level API with code\-generation\. More information can be found in kdb\-gen\-highlevel(1) \fIkdb\-gen\-highlevel\.md\fR
.SH "EXAMPLES"
Examples can be found on the man\-pages of each template\.
.SH "SEE ALSO"
.IP "\(bu" 4
kdb(1) \fIkdb\.md\fR for general information about the \fBkdb\fR tool\.
.IP "\(bu" 4
elektra\-key\-names(7) \fIelektra\-key\-names\.md\fR for an explanation of key names\.
.IP "" 0

