.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-CHANGE\-STORAGE\-SYMLINK" "" "August 2019" ""
.SH "NAME"
\fBkdb\-change\-storage\-symlink\fR \- Changes the default storage symlink
.SH "SYNOPSIS"
\fBkdb change\-storage\-symlink <storage>\fR
.P
Where \fBstorage\fR is the name of the new default storage plugin\.
.SH "DESCRIPTION"
This command updates the symlink pointing to the default storage if \fBstorage\fR is a valid storage plugin\.
.SH "EXAMPLES"
Set default storage plugin to ini:
.br
\fBkdb change\-storage\-symlink ini\fR
.SH "SEE ALSO"
.IP "\(bu" 4
kdb\-change\-resolver\-symlink(1) \fIkdb\-change\-resolver\-symlink\.md\fR
.IP "" 0

