.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre1
.TH "KDB\-GLOBAL\-UMOUNT" "1" "September 2022" ""
.SH "NAME"
\fBkdb\-global\-umount\fR \- Unmount a global plugin from the key database
.SH "SYNOPSIS"
\fBkdb global\-umount <name>\fR
.SH "DESCRIPTION"
Unmount a global plugin from the key database\.
.SH "OPTIONS"
.TP
\fB\-H\fR, \fB\-\-help\fR
Show the man page\.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info\.
.TP
\fB\-p\fR, \fB\-\-profile <profile>\fR
Use a different kdb profile\.
.TP
\fB\-C\fR, \fB\-\-color <when>\fR
Print never/auto(default)/always colored output\.
.SH "EXAMPLES"
.nf
if [ \-f "$(kdb file system:/elektra/globalplugins)" ]; then mv "$(kdb file system:/elektra/globalplugins)" "globalplugins\.bak"; else touch "globalplugins\.rm"; fi

sudo kdb global\-mount tracer

sudo kdb global\-mount
# STDOUT\-REGEX: \.*tracer\.*

sudo kdb global\-umount tracer

sudo kdb global\-mount
#>


if [ \-f "globalplugins\.rm" ]; then rm "$(kdb file system:/elektra/globalplugins)" "globalplugins\.rm"; else mv "globalplugins\.bak" "$(kdb file system:/elektra/globalplugins)"; fi
.fi
.SH "SEE ALSO"
.IP "\(bu" 4
kdb\-global\-mount(1) \fIkdb\-global\-mount\.md\fR\.
.IP "\(bu" 4
elektra\-mounting(7) \fIelektra\-mounting\.md\fR\.
.IP "\(bu" 4
elektra\-plugins\-framework(7) \fI/doc/dev/plugins\-framework\.md\fR\.
.IP "" 0

