.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-MOUNT" "1" "June 2023" ""
.SH "NAME"
\fBkdb\-mount\fR \- Mount a file to the key database
.SH "SYNOPSIS"
\fBkdb mount [<path> <mount point>] [<plugin> [<config>] [\.\.]]\fR
.br
.IP "\(bu" 4
Where \fBpath\fR is the path to the file the user wants to mount\. See \fBkdb plugin\-info resolver\fR for details what an absolute and relative path means\. See also IMPORTANT below\.
.IP "\(bu" 4
\fBmountpoint\fR is where in the key database the new backend should be mounted\. For a cascading mount point, \fBmountpoint\fR should start with \fB/\fR\. See also IMPORTANT below\.
.IP "\(bu" 4
A list of such plugins with a configuration for each of them can be given:
.IP "\(bu" 4
\fBplugin\fR should be an Elektra plugin\.
.IP "\(bu" 4
Plugins may be followed by a \fB,\fR separated list of \fBkeys=values\fR pairs which will be used as plugin configuration\.
.IP "" 0

.IP "" 0
.SH "DESCRIPTION"
This command allows a user to persistently mount a new \fIbackend\fR\. Mounting in Elektra allows the user to mount a file into the current key database like a user may mount a partition into the current file system\. This functionality is key to Elektra as it allows users to build a global key database comprised of many different configuration files\.
.P
A backend acts as a worker to allow Elektra to interpret configuration files as keys in the central key database such that any edits to the keys are reflected in the file and vice versa\. Additionally, the user can use this command to list the currently mounted backends by running the command with no arguments\. More about mounting is explained in elektra\-mounting(7) \fIelektra\-mounting\.md\fR\.
.SH "IMPORTANT"
This command writes into the \fB/etc\fR directory to make the mounting persistent\. As such it requires root permissions\. Use \fBkdb file system:/elektra/mountpoints\fR to find out where exactly it will write to\.
.P
Absolute paths are still relative to their namespace (see \fBkdb plugin\-info resolver\fR)\. Only system+spec mount points are actually absolute\. Read elektra\-namespaces(7) \fIelektra\-namespaces\.md\fR for further information\.
.P
For cascading mount points (starting with \fB/\fR) a mount point for the namespace \fBdir\fR, \fBuser\fR and \fBsystem\fR is created\. Each of this mount point uses a different configuration file, either below current directory, below home directory or anywhere in the system\. Use \fBkdb file <path>\fR to determine where the file(s) are\.
.SH "OPTIONS"
.IP "\(bu" 4
\fB\-H\fR, \fB\-\-help\fR: Show usage of command\.
.IP "\(bu" 4
\fB\-V\fR, \fB\-\-version\fR: Print version info\.
.IP "\(bu" 4
\fB\-C\fR, \fB\-\-color <when>\fR: Print never/auto(default)/always colored output\.
.IP "\(bu" 4
\fB\-v\fR, \fB\-\-verbose\fR: Explain what is happening\. Prints additional information in case of errors/warnings\.
.IP "\(bu" 4
\fB\-d\fR, \fB\-\-debug\fR: Give debug information or ask debug questions (in interactive mode)\. Prints additional information in case of errors/warnings\.
.IP "\(bu" 4
\fB\-q\fR, \fB\-\-quiet\fR: Suppress non\-error messages\.
.IP "\(bu" 4
\fB\-i\fR, \fB\-\-interactive\fR: Instead of passing all mounting information by parameters ask the user interactively\.
.IP "\(bu" 4
\fB\-s\fR, \fB\-\-strategy\fR: (experimental, use with care) By default mounting is rejected if the mountpoint already exists\. With the strategy \fIunchanged\fR you can change the behavior to be successful if \fIexactly\fR the same config would be written (see #1306 why this does not always work correctly)\.
.IP "\(bu" 4
\fB\-R\fR, \fB\-\-resolver <resolver>\fR Specify the resolver plugin to use if no resolver is given, the default resolver is used\. See also \fIbelow in KDB\fR\.
.IP "\(bu" 4
\fB\-0\fR, \fB\-\-null\fR: Use binary 0 termination\.
.IP "\(bu" 4
\fB\-1\fR, \fB\-\-first\fR: Suppress the first column\.
.IP "\(bu" 4
\fB\-2\fR, \fB\-\-second\fR: Suppress the second column\.
.IP "\(bu" 4
\fB\-c\fR, \fB\-\-plugins\-config <plugins\-config>\fR: Add a plugin configuration for all plugins\.
.IP "\(bu" 4
\fB\-W\fR, \fB\-\-with\-recommends\fR: Also add recommended plugins and warn if they are not available\.
.IP "\(bu" 4
\fB\-f\fR, \fB\-\-force\fR: Unmount before mounting: Does not fail on already existing mount points\.
.IP "" 0
.SH "KDB"
.TP
\fB/sw/elektra/kdb/#0/current/quiet\fR
Same as \fB\-q\fR: Suppress default messages\.
.TP
\fB/sw/elektra/kdb/#0/current/resolver\fR
The resolver that will be added automatically, if \fB\-R\fR is not given\.
.TP
\fB/sw/elektra/kdb/#0/current/plugins\fR
It contains a space\-separated list of plugins and their configs which are added automatically (by default sync)\. The plugin\-configuration syntax is as described above in the \fIsynopsis\fR\.
.SH "EXAMPLES"
To list the currently mounted backends:
.br
\fBkdb mount\fR
.P
To mount a system configuration file using the ini format:
.br
\fBkdb mount /etc/configuration\.ini system:/example ini\fR
.P
Print a null\-terminated output of paths and backend names:
.br
\fBkdb mount \-02 | xargs \-0n 2 echo\fR
.P
To mount the /etc/file system file with two plugins with a respective configuration option each:
.br
\fBkdb mount /etc/file system:/file plugin1 plugin1config=config1 plugin2 plugin2config=config2\fR
.P
To mount the /etc/file system file with two plugins and setting both to be verbose:
.br
\fBkdb mount \-c verbose=1 /etc/file system:/file plugin1 plugin2\fR
.P
To recode and rename a configuration file using Elektra:
.br
\fBkdb mount recode\.txt dir:/recode ni rename cut=path iconv to=utf8,from=latin1\fR
.SH "SEE ALSO"
.IP "\(bu" 4
elektra\-glossary(7) \fIelektra\-glossary\.md\fR\.
.IP "\(bu" 4
kdb\-spec\-mount(1) \fIkdb\-spec\-mount\.md\fR\.
.IP "\(bu" 4
kdb\-umount(1) \fIkdb\-umount\.md\fR\.
.IP "\(bu" 4
kdb\-mountOdbc(1) \fIkdb\-mountOdbc\.md\fR\.
.IP "\(bu" 4
elektra\-mounting(7) \fIelektra\-mounting\.md\fR\.
.IP "" 0

