.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-CHANGE\-RESOLVER\-SYMLINK" "" "August 2019" ""
.SH "NAME"
\fBkdb\-change\-resolver\-symlink\fR \- Changes the default resolver symlink
.SH "SYNOPSIS"
\fBkdb change\-resolver\-symlink <resolver>\fR
.P
Where \fBresolver\fR is the name of the new default resolver plugin\.
.SH "DESCRIPTION"
This command updates the symlink pointing to the default resolver if \fBresolver\fR is a valid resolver plugin\.
.SH "EXAMPLES"
Set default resolver plugin to resolver_fm_hpu_b:
.br
\fBkdb change\-resolver\-symlink resolver_fm_hpu_b\fR
.SH "SEE ALSO"
.IP "\(bu" 4
kdb\-change\-storage\-symlink(1) \fIkdb\-change\-storage\-symlink\.md\fR
.IP "" 0

