.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-REMOUNT" "1" "November 2020" ""
.SH "NAME"
\fBkdb\-remount\fR \- Use an existing backend to mount a new file
.SH "SYNOPSIS"
\fBkdb remount <new path> <new mount point> <existing mount point>\fR
.P
Where \fBnew path\fR is the path to the file the user wants to mount, (Absolute for system files, relative for user files)
.br
\fBnew mount point\fR is where in the key database the new configuration file should be mounted at, (For a cascading mount pount, \fBmountpoint\fR should start with \fB/\fR)
.br
and \fBexisting mount point\fR is the mount point where the existing backend is mounted\.
.br
.SH "DESCRIPTION"
This command allows a user to use an existing backend (such as one from a previous mount) to mount a new configuration file to a new mount point in the key database\.
.br
.SH "OPTIONS"
.TP
\fB\-H\fR, \fB\-\-help\fR
Show the man page\.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info\.
.TP
\fB\-p\fR, \fB\-\-profile <profile>\fR
Use a different kdb profile\.
.TP
\fB\-C\fR, \fB\-\-color <when>\fR
Print never/auto(default)/always colored output\.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Explain what is happening\. Prints additional information in case of errors/warnings\.
.TP
\fB\-d\fR, \fB\-\-debug\fR
Give debug information or ask debug questions (in interactive mode)\. Prints additional debug information in case of errors/warnings\.
.TP
\fB\-i\fR, \fB\-\-interactive\fR
Instead of passing all information by parameters ask the user interactively\.
.SH "EXAMPLES"
To mount a new file using an existing backend that is mounted to \fBsystem:/example\fR:
.br
\fBkdb remount /etc/configuration2\.ini system:/example2 system:/example\fR
.br

