.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-LIST\-TOOLS" "1" "November 2019" ""
.SH "NAME"
\fBkdb\-list\-tools\fR \- List all external tools available to Elektra
.SH "SYNOPSIS"
\fBkdb list\-tools\fR
.SH "DESCRIPTION"
This command lists all the external tools that are available to Elektra\. In the first line it prints where external tools are located\.
.P
The tool itself is extern\.
.SH "ENVIRONMENT"
.TP
\fBKDB_EXEC_PATH\fR
Path to additional external tools\. Can contain multiple paths separated with :\.
.SH "OPTIONS"
Currently no option provided\.
.SH "SEE ALSO"
.IP "\(bu" 4
\fBkdb list\-commands\fR to list internal kdb commands
.IP "" 0

