.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-TEST" "1" "May 2023" ""
.SH "NAME"
\fBkdb\-test\fR \- Run test(s) on the key database
.SH "SYNOPSIS"
\fBkdb test <path> [<test\-name> \|\.\|\.\|\.]\fR
.br
.P
Where \fBpath\fR is the path the user wishes to perform the test under\. The option \fBtest\-name\fR argument is used to specify which test(s) to run\. To run multiple tests, each should be named with a trailing space\.
.br
If no \fBtest\-name\fR is provided, all the tests will be run\.
.br
.SH "DESCRIPTION"
This command is used to run part or all of the key database test suite\.
.br
These tests allow one to user to verify that a backend is capable of storing and retrieving all kinds of configuration keys and values\.
.br
.P
The following tests are available: basic string umlauts binary naming meta
.br
.SH "OPTIONS"
.TP
\fB\-H\fR, \fB\-\-help\fR
Show usage of command\.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info\.
.TP
\fB\-C\fR, \fB\-\-color <when>\fR
Print never/auto(default)/always colored output\.
.SH "EXAMPLES"
To run all tests below the \fBuser:/tests/example\fR key:
.br
\fBkdb test user:/tests/example\fR
.br
.P
To run the \fBbinary\fR and \fBnaming\fR tests:
.br
.IP "" 4
.nf
kdb test user:/tests/example binary naming
# RET: 0

# clean\-up
kdb rm \-r user:/tests/example
.fi
.IP "" 0
.SH "SEE ALSO"
.IP "\(bu" 4
elektra\-key\-names(7) \fIelektra\-key\-names\.md\fR for an explanation of key names\.
.IP "" 0

