.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-INSTALL\-CONFIG\-FILE" "1" "November 2020" ""
.SH "NAME"
\fBkdb\-install\-config\-file\fR \- Install configuration files in Elektra
.SH "SYNOPSIS"
\fBkdb install\-config\-file <elektra path> <config file> [<format>]\fR
.IP "\(bu" 4
\fB<elektra path>\fR is a path in Elektra
.IP "\(bu" 4
\fB<config file>\fR is some file on the filesystem
.IP "" 0
.P
\fBline\fR will be used as \fB<format>\fR if \fB<format>\fR is unspecified\.
.P
The script has to be called as administrator (e\.g\. with \fBsudo\fR)\.
.SH "DESCRIPTION"
This script installs or merges configuration files from the file system into Elektra\. There are two possible scenarios:
.IP "1." 4
You use the script for the first time for a file\. Then \fB<elektra path>\fR is empty\. The script
.IP "1." 4
copies \fB<config file>\fR into a special path to preserve origin version\.
.IP "2." 4
mounts \fB<config file>\fR into \fB<elektra path>\fR as our version\. This version can then be safely modified\.
.IP "" 0

.IP "2." 4
You have already used the script for a previous version of the file\. In this case \fB<elektra path>\fR already contains data the script performs a three\-way merge (using \fBkdb merge\fR) between the file at \fB<config file>\fR (their), the \fB<elektra path>\fR (our) and the preserved key set (base) from step 1 in scenario 1\.
.IP "" 0
.SH "EXAMPLES"
To install the config file at \fB~/\.config/installing\.ini\fR we can use the following command
.P
\fBkdb install\-config\-file user:/tests/installing installing\.ini ini\fR
