.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "KDB\-FSTAB" "1" "June 2019" "" ""
.
.SH "NAME"
\fBkdb\-fstab\fR \- Create a new fstab entry
.
.SH "SYNOPSIS"
\fBkdb fstab <path> <fs_spec> <fs_file> <fs_vfstype> <fs_mntops>\fR
.
.P
Where \fBpath\fR is the path where the created keys should be stored in the key database\. The other arguments are as described in fstab(5)\.
.
.SH "DESCRIPTION"
This command is used to create a new \fBfstab\fR entry\.
.
.br
Due to the unique format of \fBfstab\fR entries, it is not possible to set individual elements of new \fBfstab\fR entries\.
.
.br
This command is used to gather all the data needed to create a single \fBfstab\fR entry in order to bypass the issue of not being able to set individual elements\.
.
.br
This command will create the new entry with a name of \fBZZZNewFstabName\fR which should then automatically be renamed by the \fBfstab\fR plugin\.
.
.br
.
.SH "OPTIONS"
.
.TP
\fB\-H\fR, \fB\-\-help\fR
Show the man page\.
.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info\.
.
.TP
\fB\-p\fR, \fB\-\-profile <profile>\fR
Use a different kdb profile\.
.
.TP
\fB\-C\fR, \fB\-\-color <when>\fR
Print never/auto(default)/always colored output\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Explain what is happening\. Prints additional information in case of errors/warnings\.
.
.TP
\fB\-d\fR, \fB\-\-debug\fR
Give debug information\. Prints additional debug information in case of errors/warnings\.
.
.SH "EXAMPLES"
To create an fstab entry to mount \fBdev/sdb1\fR to \fB/media/external\fR stored in the key \fBsystem/fstab/sdb1\fR:
.
.br
\fBkdb fstab system/fstab/sdb1 /dev/sdb1 /media/external ext4 errors=remount\-ro\fR
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
Use \fBkdb info fstab\fR to get information about the fstab plugin\.
.
.IP "\(bu" 4
elektra\-key\-names(7) \fIelektra\-key\-names\.md\fR for an explanation of key names\.
.
.IP "" 0

