.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "README" "" "August 2018" ""
The ZeroMQ message hub is a lightweight message hub for distributing notifications for "zeromqsend" and "zeromqrecv" plugins\. This hub is intended for local use via the IPC transport or in a controlled network environment using the TCP transport\. The hub does not feature authentication or encryption\.
.SH "Usage"
The hub can be controlled using the CLI commands "kdb run\-hub\-zeromq" for starting and "kdb stop\-hub\-zeromq" for stopping\.
.SH "Configuration"
The endpoints the hub binds to can be configured using the "/sw/elektra/hub\-zeromq/#0/current/bind_xsub" and "/sw/elektra/hub\-zeromq/#0/current/bind_xpub" configuration keys in KDB\.
.P
The default settings match the default settings for the zeromq plugins which are "tcp://127\.0\.0\.1:6000" for XSUB and "tcp://127\.0\.0\.1:6001" for XPUB\.
