.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-PLUGIN\-CHECK\-ENV\-DEP" "" "October 2019" ""
.SH "NAME"
\fBkdb\-plugin\-check\-env\-dep\fR \- Checks which mount points are influenced by environment variables
.SH "SYNOPSIS"
\fBkdb check\-env\-dep\fR
.SH "DESCRIPTION"
This command checks which mount point is influenced by changes to environment variables\. \fBPATH\fR and \fBKDB\fR are skipped for reasons\.
.SH "SEE ALSO"
.IP "\(bu" 4
kdb\-mount\-list\-all\-files(1) \fIkdb\-mount\-list\-all\-files\.md\fR
.IP "" 0

