.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "KDB\-DIRKEY" "1" "August 2021" ""
.SH "NAME"
\fBkdb\-dirkey\fR \- Get the directory name of a key name including namespace
.SH "SYNOPSIS"
\fBkdb dirkey <key name>\fR
.P
Where \fBkey name\fR is the name of the key\.
.SH "DESCRIPTION"
This command is used to retrieve the directory name of a key, including namespace\.
.SH "RETURN VALUES"
This command will return the following values as an exit status:
.TP
0
No errors\.
.TP
7
invalid key name passed, see kdb(1) \fIkdb\.md\fR for a list of return codes used by kdb\.
.SH "OPTIONS"
.TP
\fB\-n\fR, \fB\-\-no\-newline\fR
Suppress the newline at the end of the output\.
.SH "EXAMPLES"
```sh kdb dirkey user:/key/subkey #> user:/key
.P
kdb dirkey / #> / ```
.SH "SEE ALSO"
.IP "\[ci]" 4
Use kdb\-dirname(1) \fIkdb\-dirname\.md\fR to obtain the directory of a key \fIwithout namespace included\fR\.
.IP "\[ci]" 4
See kdb\-namespace(1) \fIkdb\-namespace\.md\fR, kdb\-basename(1) \fIkdb\-basename\.md\fR for other namepart extraction operations\.
.IP "\[ci]" 4
The Unix analogue [DIRNAME(1)]\.
.IP "\[ci]" 4
To get keys in shell scripts, you can use kdb\-sget(1) \fIkdb\-sget\.md\fR\.
.IP "\[ci]" 4
elektra\-key\-names(7) \fIelektra\-key\-names\.md\fR for an explanation of key names\.
.IP "" 0

