.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-RESET" "1" "August 2019" ""
.SH "NAME"
\fBkdb\-reset\fR \- Resets the whole KDB
.SH "SYNOPSIS"
\fBkdb reset \-f\fR
.SH "DESCRIPTION"
Resets the whole KDB\.
.SH "WARNING"
These changes cannot be undone, please use with care! This command writes into the \fB/etc\fR directory and as such it requires root permissions\.
.SH "OPTIONS"
.TP
\fB\-H\fR, \fB\-\-help\fR
Show the man page\.
.SH "SEE ALSO"
.IP "\(bu" 4
kdb\-backup(1) \fIkdb\-backup\.md\fR\.
.IP "\(bu" 4
kdb\-stash(1) \fIkdb\-stash\.md\fR\.
.IP "\(bu" 4
elektra\-mounting(7) \fIelektra\-mounting\.md\fR\.
.IP "" 0

