.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-LIST\-COMMANDS" "1" "May 2023" ""
.SH "NAME"
\fBkdb\-list\-commands\fR \- List commands available to Elektra
.SH "SYNOPSIS"
\fBkdb list\-commands\fR
.SH "DESCRIPTION"
This command will list all internal kdb commands\. The output is suitable to be processed from other tools as long as \fB\-v\fR is not used\.
.SH "OPTIONS"
.TP
\fB\-H\fR, \fB\-\-help\fR
Show usage of command\.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info\.
.TP
\fB\-C\fR, \fB\-\-color <when>\fR
Print never/auto(default)/always colored output\.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Also output some explanation for every command\. The command names are bold if color is turned on\. In the first line it will add how many commands exist\.
.TP
\fB\-0\fR, \fB\-\-null\fR
Use binary 0 termination
.SH "EXAMPLES"
To get a list of all available commands with their help text: \fBkdb list\-commands \-v\fR
.SH "SEE ALSO"
.IP "\(bu" 4
\fBkdb list\-tools\fR for external kdb commands
.IP "" 0

