.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-RECORD\-STOP" "1" "May 2023" ""
.SH "NAME"
\fBkdb\-record\-stop\fR \- Stop session recording
.SH "SYNOPSIS"
\fBkdb record\-stop\fR
.br
.SH "DESCRIPTION"
This command stops the current recording session\. Changes that are made to KDB after this command will no longer be recorded\. The recording session will NOT be cleared\.
.SH "OPTIONS"
.TP
\fB\-H\fR, \fB\-\-help\fR
Show the man page\.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info\.
.TP
\fB\-p\fR, \fB\-\-profile <profile>\fR
Use a different kdb profile\.
.TP
\fB\-C\fR, \fB\-\-color <when>\fR
Print never/auto(default)/always colored output\.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Explain what is happening\. Prints additional information in case of errors/warnings\.
.TP
\fB\-d\fR, \fB\-\-debug\fR
Give debug information\. Prints additional debug information in case of errors/warnings\.
.SH "RETURN VALUE"
.TP
0
Successful\.
.TP
1\-10
standard exit codes, see kdb(1) \fIkdb\.md\fR
.TP
11
An error occurred during stopping the recording\.
.SH "SEE ALSO"
.IP "\(bu" 4
kdb\-record\-start(1) \fIkdb\-record\-start\.md\fR on how to start the recording session
.IP "\(bu" 4
kdb\-record\-state(1) \fIkdb\-record\-state\.md\fR on how to get information about the current recording session
.IP "\(bu" 4
kdb\-record\-reset(1) \fIkdb\-record\-reset\.md\fR on how to clear the recording session
.IP "" 0

