.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-BACKUP" "" "November 2021" ""
.SH "NAME"
\fBkdb\-backup\fR \- Make a backup of current KDB
.SH "SYNOPSIS"
\fBkdb backup\fR
.SH "DESCRIPTION"
This command will backup the \fBsystem\fR, \fBuser\fR and \fBspec\fR configuration\. Afterwards a timestamp, which can be used to restore everything, will be printed\.
.P
The backup will be done in the \fB/var/tmp\fR directory, so make sure the backup is not deleted\.
.SH "EXAMPLES"
.nf
kdb backup
#> kdb restore 1500000000
.fi
.SH "SEE ALSO"
.IP "\(bu" 4
kdb\-stash(1) \fIkdb\-stash\.md\fR
.IP "\(bu" 4
kdb\-restore(1) \fIkdb\-restore\.md\fR
.IP "" 0

