.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-HELP" "1" "November 2020" ""
.SH "NAME"
\fBkdb\-help\fR \- Show man page for elektra tools
.SH "SYNOPSIS"
.nf
kdb help <tool>
kdb \-\-help <tool>
kdb \-H <tool>
.fi
.SH "DESCRIPTION"
Show a man page for one of Elektra’s tools\. Note that \fBkdb <tool> \-\-help\fR might have a different behavior, depending on the tool\.
.P
Also note that, no additional commandline options are allowed for this kind of invocation\. If you want that use \fB\-\-help\fR or \fB\-H\fR after \fB<tool>\fR\.
.SH "KDB"
.TP
\fB/sw/elektra/kdb/#0/current/man\fR
The man(1) utility to be used\. Defaults to /usr/bin/man
.SH "EXAMPLES"
Show how to set keys: \fBkdb help set\fR
.P
Use the info program as man page viewer for the current user: \fBkdb set user:/sw/elektra/kdb/#0/current/man /usr/bin/info\fR
