.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-MOUNT\-LIST\-ALL\-FILES" "" "November 2020" ""
.SH "NAME"
\fBkdb\-mount\-list\-all\-files\fR \- List all mounted files
.SH "SYNOPSIS"
\fBkdb mount\-list\-all\-files\fR
.SH "DESCRIPTION"
This command prints a sorted list of all files under the control of Elektra
.SH "EXAMPLES"
.nf
kdb mount
#> none on system:/info/elektra/constants with name system:/info/elektra/constants
#> /usr/local/share/doc/elektra/CONTRACT\.ini on system:/info/elektra/contract/#0 with name system:/info/elektra/contract/#0
#> none on system:/info/elektra/desktop with name system:/info/elektra/desktop
#> /usr/local/share/doc/elektra/METADATA\.ini on system:/info/elektra/metadata/#0 with name system:/info/elektra/metadata/#0
#> none on system:/info/elektra/uname with name system:/info/elektra/uname
#> /tmp/test\.ini on system:/test with name system:/test

kdb mount\-list\-all\-files
#> none
#> /tmp/test\.ini
#> /usr/local/share/doc/elektra/CONTRACT\.ini
#> /usr/local/share/doc/elektra/METADATA\.ini
.fi

