.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1.pre3
.TH "KDB\-META\-SET" "1" "March 2023" ""
.SH "NAME"
\fBkdb\-meta\-set\fR \- Set the value of a metakey
.SH "SYNOPSIS"
\fBkdb meta set <key name> <metaname> [<metavalue>]\fR
.P
Where \fBkey name\fR is the name of the key that the metakey is associated with, \fBmetaname\fR is the name of the metakey the user would like to set the value of (or create), and \fBmetavalue\fR is the value the user wishes to set the metakey to\. If no \fBmetavalue\fR is given, the metakey will be removed\.
.SH "DESCRIPTION"
This command allows the user to set the value of an individual metakey\. If a (non\-cascading) key does not already exist and the user tries setting a metakey associated with it, the key will be created with a null value\. If a cascading key is given that does not resolve to an actual key, the operation is aborted\.
.P
There is some special handling for the metadata atime, mtime and ctime\. They will be converted to time_t\.
.SH "OPTIONS"
.TP
\fB\-H\fR, \fB\-\-help\fR
Show the man page\.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version info\.
.TP
\fB\-p\fR, \fB\-\-profile <profile>\fR
Use a different kdb profile\.
.TP
\fB\-C\fR, \fB\-\-color <when>\fR
Print never/auto(default)/always colored output\.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Explain what is happening\. Prints additional information in case of errors/warnings\.
.TP
\fB\-d\fR, \fB\-\-debug\fR
Give debug information\. Prints additional debug information in case of errors/warnings\.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Suppress non\-error messages\.
.TP
\fB\-f\fR, \fB\-\-force\fR
Do not perform cascading KDB operations if the key provided has a namespace\. For example, this bypasses validation specified in the spec: namespace for the given key\.
.SH "RETURN VALUES"
This command will return the following values as an exit status:
.br
.TP
0
No errors\.
.TP
11
Key not found\. (Invalid \fBpath\fR)
.TP
12
Setting a non\-existing key without a namespace is not possible\.
.SH "KDB"
.TP
\fB/sw/elektra/kdb/#0/current/verbose\fR
Same as \fB\-v\fR: Explain what is happening\.
.TP
\fB/sw/elektra/kdb/#0/current/quiet\fR
Same as \fB\-q\fR: Suppress default messages\.
.SH "EXAMPLES"
To set a metakey called \fBdescription\fR associated with the key \fBuser:/example/key\fR to the value \fBHello World!\fR:
.br
\fBkdb meta set spec:/example/key description "Hello World!"\fR
.P
To create a new key \fBspec:/example/newkey\fR with a null value (if it did not exist before) and a metakey \fBnamespace/#0\fR associated with it to the value \fBsystem\fR:
.br
\fBkdb meta set /example/newkey "namespace/#0" system\fR
.P
To create an override link for a \fB/test\fR key:
.IP "" 4
.nf
kdb set /overrides/test "example override"
sudo kdb meta set spec:/test override/#0 /overrides/test
.fi
.IP "" 0
.P
To remove it:
.IP "" 4
.nf
sudo kdb meta set spec:/test override/#0
.fi
.IP "" 0
.SH "SEE ALSO"
.IP "\(bu" 4
How to get metadata: kdb\-meta\-get(1) \fIkdb\-meta\-get\.md\fR
.IP "\(bu" 4
elektra\-metadata(7) \fIelektra\-metadata\.md\fR for an explanation of the metadata concepts\.
.IP "\(bu" 4
elektra\-key\-names(7) \fIelektra\-key\-names\.md\fR for an explanation of key names\.
.IP "" 0

