TERM
STREAM_START = 1
STREAM_END = 2
COMMENT = 3
PLAIN_SCALAR = 4
SINGLE_QUOTED_SCALAR = 5
DOUBLE_QUOTED_SCALAR = 6
MAP_START = 7
MAP_END = 8
KEY = 9
VALUE = 10
SEQUENCE_START = 11
SEQUENCE_END = 12
ELEMENT = 13;

yaml : STREAM_START empty_child STREAM_END # 1 ;
empty_child : empty # 0
            | child # 0
            ;

empty : comments_empty # empty ();

child_comments_empty : child # 0
                     | comments
                     |
                     ;

child : comments_empty node comments_empty # 1 ;
node : value    # value (0)
     | map      # 0
     | sequence # 0
     ;

comments_empty : comments | ;
comments : COMMENT
         | comments COMMENT
         ;

value : scalar # 0 ;
scalar : PLAIN_SCALAR         # 0
       | SINGLE_QUOTED_SCALAR # 0
       | DOUBLE_QUOTED_SCALAR # 0
       ;

map : MAP_START pairs MAP_END # 1 ;
pairs : pair       # 0
      | pairs pair # pairs (0 1)
      | pairs error
      ;
pair : KEY key VALUE child_comments_empty # pair (1 3) ;
key : scalar # key (0) ;

sequence : SEQUENCE_START elements SEQUENCE_END # sequence(1) ;
elements : element # 0
         | elements element # elements(0 1)
         | elements error
         ;
element : ELEMENT child # element(1) ;
