/**
 * @file
 *
 * @brief Elektra error codes.
 *
 * @copyright BSD License (see doc/LICENSE.md or http://www.libelektra.org)
 */

#ifndef ELEKTRA_ERROR_CODES_H
#define ELEKTRA_ERROR_CODES_H

// TODO Automatically generate this file from the error specification file.

typedef enum {
    ELEKTRA_ERROR_CODE_GENERAL_PARSE_ERROR = 10,
    ELEKTRA_ERROR_CODE_COULD_NOT_OPEN_CONFIGURATION_FILE = 26,
    ELEKTRA_ERROR_CODE_KEY_DATABASE_MODIFIED = 30,
    ELEKTRA_ERROR_CODE_INVALID_KEY = 59,
    ELEKTRA_ERROR_CODE_NOEOF = 60,
    ELEKTRA_ERROR_CODE_READ_FILE_FAILED = 76,
    ELEKTRA_ERROR_CODE_MALLOC_ERROR = 87,
    ELEKTRA_ERROR_CODE_WRONG_SYNC_STATE = 107,
    ELEKTRA_ERROR_CODE_FAILED_TO_INIT_CRYPTO = 125,
    ELEKTRA_ERROR_CODE_INTERNAL_ERROR = 126,
    ELEKTRA_ERROR_CODE_CRYPTO_ENCRYPT_FAILED = 127,
    ELEKTRA_ERROR_CODE_CRYPTO_DECRYPT_FAILED = 128,
    ELEKTRA_ERROR_CODE_CRYPTO_DECRYPT_WARNING = 129,
    ELEKTRA_ERROR_CODE_CRYPTO_CONFIG_FAULT = 130,
    ELEKTRA_ERROR_CODE_COULD_NOT_GET_CURRENT_DIR = 146,
    ELEKTRA_ERROR_CODE_ISSUE_WHILE_INTERFACING_WITH_GIT = 147,
    ELEKTRA_ERROR_CODE_GIT_CONFLICT = 148,
    ELEKTRA_ERROR_CODE_VALIDATION_OF_PASSWD_FAILED = 149,
    ELEKTRA_ERROR_CODE_FAILED_TO_GENERATE_MASTER_PASSWORD = 150,
    ELEKTRA_ERROR_CODE_ERROR_IN_GPG_MODULE = 151,
    ELEKTRA_ERROR_CODE_CRYPTO_CONFIGURATION_INVALID = 152,
    ELEKTRA_ERROR_CODE_INVALID_BOOL = 153,
    ELEKTRA_ERROR_CODE_INVALID_BOOL_WARNING = 154,
    ELEKTRA_ERROR_CODE_FAILED_TO_EXTRACT_BLOCK = 155,
    ELEKTRA_ERROR_CODE_END_OF_BLOCK_NOT_FOUND = 156,
    ELEKTRA_ERROR_CODE_BASE64_WARNING = 157,
    ELEKTRA_ERROR_CODE_COULD_NOT_INCREMENT = 158,
    ELEKTRA_ERROR_CODE_NON_REQURED_KEY_FOUND = 159,
    ELEKTRA_ERROR_CODE_FAILED_TO_OVERWRITE = 160,
    ELEKTRA_ERROR_CODE_CANNOT_REPLACE = 161,
    ELEKTRA_ERROR_CODE_FAILED_TO_RESTORE_TIMESTAMP = 163,
    ELEKTRA_ERROR_CODE_FAILED_TO_UPLOAD_CONFIG_FILE = 164,
    ELEKTRA_ERROR_CODE_COULD_NOT_FETCH_FILE = 165,
    ELEKTRA_ERROR_CODE_FAILED_TO_FETCH_CONFIG_FILE = 166,
    ELEKTRA_ERROR_CODE_INVALID_PLUGIN_CONFIG = 167,
    ELEKTRA_ERROR_CODE_VALIDATION_OF_DATETIME_FAILED = 168,
    ELEKTRA_ERROR_CODE_COULD_NOT_STAT_FILE = 169,
    ELEKTRA_ERROR_CODE_INVALID_RANGE_SYNTAX = 170,
    ELEKTRA_ERROR_CODE_VALUE_NOT_WITHIN_RANGE = 171,
    ELEKTRA_ERROR_CODE_MULTIFILE_GLOBBING_FAILED = 172,
    ELEKTRA_ERROR_CODE_INVALID_LINE_FORMAT_PATTERN = 173,
} ElektraErrorCode;

#endif //ELEKTRA_ERROR_CODES_H
